# Generated by Django 3.2.4 on 2022-05-06 00:58

import actions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.CharField(default=actions.models.StringKeyGenerator.__call__, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('initiator', models.CharField(blank=True, max_length=250, null=True)),
                ('dateEntered', models.DateTimeField(auto_now_add=True)),
                ('actionUri', models.CharField(blank=True, max_length=250, null=True)),
                ('read', models.BooleanField(default=False, help_text='Message was read by user but not acted on')),
                ('completed', models.BooleanField(default=False, help_text='Message has been acted upon and should be archived as complete.')),
                ('settings', models.JSONField(default={'has_approve_decline': False, 'has_delegate': False, 'has_goto_resource': False})),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.action')),
            ],
        ),
    ]
