# Generated by Django 5.0.1 on 2024-05-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynapages", "0003_alter_page_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="system",
            field=models.BooleanField(default=False, verbose_name="System Page"),
        ),
    ]
