# Generated by Django 5.0.1 on 2024-05-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynapages", "0004_page_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="staff",
            field=models.BooleanField(
                default=False, verbose_name="Includes Staff Dashboard Mode"
            ),
        ),
    ]
