# Generated by Django 5.0.1 on 2024-05-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynapages", "0005_widget_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="widget_mode",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Page Widget Mode (optional)",
            ),
        ),
    ]
