# Generated by Django 5.0.1 on 2024-06-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynapages", "0006_page_widget_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="profile_page",
            field=models.BooleanField(default=False, verbose_name="Profile Page"),
        ),
    ]
