# Generated by Django 5.0.1 on 2024-06-14 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynapages", "0007_page_profile_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="template",
            field=models.ForeignKey(
                limit_choices_to={"page_template": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="dynapages.templates",
                verbose_name="Dynapage Template",
            ),
        ),
    ]
