# Generated by Django 4.0.4 on 2022-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0009_remove_pagewidget_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='app',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='App Name ID'),
        ),
        migrations.AddField(
            model_name='widget',
            name='setup_form',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Setup Form Class Name'),
        ),
        migrations.AddField(
            model_name='widget',
            name='setup_required',
            field=models.BooleanField(default=False, verbose_name='Setup Required'),
        ),
    ]
