# Generated by Django 3.2.4 on 2021-06-27 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_staffassignment_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(max_length=100, verbose_name="Legal First Name"),
                ),
                (
                    "lastName",
                    models.CharField(max_length=100, verbose_name="Legal Last Name"),
                ),
                (
                    "fanName",
                    models.CharField(max_length=100, verbose_name="Furry or Fan Name"),
                ),
                ("dateOfBirth", models.DateField(verbose_name="Date of Birth")),
                (
                    "felonyVerify",
                    models.BooleanField(
                        help_text="I certify that I have not been convicted of a felony",
                        verbose_name="Certify no felonies",
                    ),
                ),
                (
                    "eighteenVerify",
                    models.BooleanField(
                        help_text="I certify that I will be aged 18 or older at the time of the convention.",
                        verbose_name="18+ Verification",
                    ),
                ),
                (
                    "address1",
                    models.CharField(max_length=100, verbose_name="Address 1"),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Address 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                ("zipCode", models.CharField(max_length=100, verbose_name="ZIP Code")),
                (
                    "emergencyContact",
                    models.CharField(
                        max_length=100, verbose_name="Emergency Contact Name"
                    ),
                ),
                (
                    "emergencyContactRelation",
                    models.CharField(
                        max_length=100, verbose_name="Emergency Contact Relation"
                    ),
                ),
                (
                    "emergencyContactNumber",
                    models.CharField(
                        max_length=100, verbose_name="Emergency Contact Phone Number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="E-Mail Address"),
                ),
                (
                    "telegramHandle",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Telegram Handle",
                    ),
                ),
                (
                    "fitness",
                    models.TextField(
                        verbose_name="Why would you be a good fit for staff?"
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        verbose_name="Tell us about your skills you would bring to Furrydelphia"
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Have you worked for any other conventions? Tell us about it.",
                    ),
                ),
                (
                    "other",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Anything else you would like us to know?",
                    ),
                ),
                (
                    "openPosition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.openposition",
                    ),
                ),
            ],
        ),
    ]
