# Generated by Django 3.2.4 on 2021-10-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_staffapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("dueDate", models.DateTimeField()),
                ("departmentOnly", models.BooleanField(default=False)),
                (
                    "fromDepartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completedOn", models.DateTimeField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.tasktemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.staffassignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField(blank=True, null=True)),
                ("departmentOnly", models.BooleanField(default=False)),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
                (
                    "fromDepartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.department",
                    ),
                ),
            ],
        ),
    ]
