# Generated by Django 3.2.4 on 2021-10-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_announcement_stafftask_tasktemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="_from",
            field=models.CharField(
                blank=True, default="Department Lead", max_length=100, null=True
            ),
        ),
    ]
