# Generated by Django 3.2.4 on 2021-10-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_announcement__from"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffapplication",
            name="closeApp",
            field=models.BooleanField(default=False),
        ),
    ]
