# Generated by Django 3.2.4 on 2022-06-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staffapplication_covidcert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='covidCert',
            field=models.BooleanField(default=False, help_text='I certify that I have recieved my full series of vaccinations against COVID-19 and am considered Fully Vaccinated. (This is non-negotiable and must be certified)', verbose_name='Certify COVID-19 Vaccination'),
        ),
    ]
