# Generated by Django 4.0.4 on 2023-01-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_licensekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffassignment',
            name='primary_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
