# Generated by Django 4.0.4 on 2023-01-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_staffassignment_primary_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffassignment',
            name='rank',
            field=models.CharField(choices=[('Staff', 'Staff Member'), ('Department Assistant Director', 'Department Assistant Director'), ('Department Director', 'Department Director'), ('Board Member', 'Board Member'), ('Volunteer', 'Volunteer')], max_length=50),
        ),
    ]
