# Generated by Django 4.0.4 on 2023-01-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_staffassignment_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffassignment',
            name='grant_access_to_management_panel',
            field=models.BooleanField(default=False, help_text='Grants access to the management panel for this department if the staff is a Member and not a management position.'),
        ),
    ]
