# Generated by Django 3.2.9 on 2022-02-03 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.TextField(max_length=200, verbose_name='Template ID')),
                ('label', models.TextField(max_length=200, verbose_name='Template Label')),
                ('filename', models.TextField(max_length=200, verbose_name='Template Filename')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Template Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Template Updated')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('widget_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=200, verbose_name='Widget Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Widget Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Widget Updated')),
                ('block', models.TextField(max_length=200, verbose_name='Widget Block')),
                ('pos', models.TextField(max_length=200, verbose_name='Widget Position')),
                ('order', models.IntegerField(max_length=200, verbose_name='Widget Order')),
                ('plugin', models.TextField(default='', null=True, verbose_name='Widget Plugin')),
                ('thumbnail', models.TextField(default='', null=True, verbose_name='Widget Thumbnail')),
                ('plugin_data', models.JSONField(blank=True, null=True, verbose_name='Widget plugin-specific data')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynapages.templates', verbose_name='Widget')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=200, verbose_name='Template Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Template Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Template Updated')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynapages.templates', verbose_name='Template')),
            ],
        ),
    ]
