# Generated by Django 3.2.9 on 2022-02-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Widget',
            new_name='PageWidget',
        ),
    ]
