# Generated by Django 4.0.2 on 2022-04-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='widget_id',
            field=models.TextField(default='', max_length=200, unique=True, verbose_name='Widget ID'),
        ),
    ]
