# Generated by Django 4.0.4 on 2022-05-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0002_widget_widget_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='blog',
            field=models.BooleanField(default=False, verbose_name='Includes Blog Mode'),
        ),
        migrations.AddField(
            model_name='widget',
            name='dashboard',
            field=models.BooleanField(default=False, verbose_name='Includes Dashboard Mode'),
        ),
        migrations.AddField(
            model_name='widget',
            name='group',
            field=models.BooleanField(default=True, verbose_name='Includes Group Mode'),
        ),
        migrations.AddField(
            model_name='widget',
            name='profile',
            field=models.BooleanField(default=False, verbose_name='Includes Profile Mode'),
        ),
    ]
