# Generated by Django 3.2.9 on 2022-02-03 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0002_rename_widget_pagewidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.TextField(max_length=200, verbose_name='Widget Type')),
                ('label', models.TextField(max_length=200, verbose_name='Widget Label')),
                ('descr', models.TextField(max_length=200, verbose_name='Widget Description')),
                ('helptext', models.TextField(max_length=200, verbose_name='Widget Helptext')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Widget Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Widget Updated')),
                ('block', models.TextField(max_length=200, verbose_name='Widget Block')),
                ('pos', models.TextField(max_length=200, verbose_name='Widget Position')),
                ('version', models.IntegerField(verbose_name='Widget Vers')),
                ('plugin', models.TextField(default='', null=True, verbose_name='Widget Plugin')),
                ('widget_data', models.JSONField(blank=True, null=True, verbose_name='Widget plugin-specific data')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
        ),
        migrations.RenameField(
            model_name='pagewidget',
            old_name='widget_id',
            new_name='pagewidget_id',
        ),
        migrations.RemoveField(
            model_name='pagewidget',
            name='page_id',
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dynapages.page', verbose_name='DynaPage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='order',
            field=models.IntegerField(verbose_name='Widget Order'),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='widget',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dynapages.widget', verbose_name='Widget'),
            preserve_default=False,
        ),
    ]
