# Generated by Django 3.2.9 on 2022-02-05 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynapages', '0003_auto_20220203_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.TextField(default='', max_length=200, verbose_name='Page slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Page Created'),
        ),
        migrations.AlterField(
            model_name='page',
            name='label',
            field=models.TextField(max_length=200, verbose_name='Page Label'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynapages.templates', verbose_name='Dynapage Template'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Page Updated'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
