# Generated by Django 3.2.9 on 2022-02-05 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0004_auto_20220205_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='block',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='id',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='widget_type',
        ),
        migrations.AddField(
            model_name='templates',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived FLAG'),
        ),
        migrations.AddField(
            model_name='templates',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Blocked FLAG'),
        ),
        migrations.AddField(
            model_name='templates',
            name='frozen',
            field=models.BooleanField(default=False, verbose_name='Frozen FLAG'),
        ),
        migrations.AddField(
            model_name='templates',
            name='page_template',
            field=models.BooleanField(default=True, verbose_name='Template is used for Pages'),
        ),
        migrations.AddField(
            model_name='templates',
            name='system',
            field=models.BooleanField(default=False, verbose_name='System FLAG'),
        ),
        migrations.AddField(
            model_name='templates',
            name='widget_template',
            field=models.BooleanField(default=False, verbose_name='Template is used for Widgets'),
        ),
        migrations.AddField(
            model_name='widget',
            name='banner',
            field=models.BooleanField(default=False, verbose_name='Includes Banner Mode'),
        ),
        migrations.AddField(
            model_name='widget',
            name='footer',
            field=models.BooleanField(default=False, verbose_name='Includes Footer Mode'),
        ),
        migrations.AddField(
            model_name='widget',
            name='mainbody',
            field=models.BooleanField(default=True, verbose_name='Includes MainBody Mode'),
        ),
        migrations.AddField(
            model_name='widget',
            name='sidecol',
            field=models.BooleanField(default=False, verbose_name='Includes SideColumn Mode'),
        ),
        migrations.AddField(
            model_name='widget',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dynapages.templates', verbose_name='Dynapage Template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='widget_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
