# Generated by Django 4.0.4 on 2022-05-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0005_widget_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='thumbnail',
            field=models.TextField(blank=True, null=True, verbose_name='Widget Thumbnail'),
        ),
    ]
