# Generated by Django 3.2.9 on 2022-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0005_auto_20220205_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagewidget',
            name='block',
        ),
        migrations.RemoveField(
            model_name='pagewidget',
            name='plugin',
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='banner',
            field=models.BooleanField(default=False, verbose_name='Includes Banner Mode'),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='footer',
            field=models.BooleanField(default=False, verbose_name='Includes Footer Mode'),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='mainbody',
            field=models.BooleanField(default=True, verbose_name='Includes MainBody Mode'),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='sidecol',
            field=models.BooleanField(default=False, verbose_name='Includes SideColumn Mode'),
        ),
    ]
