# Generated by Django 3.2.9 on 2022-02-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0006_auto_20220205_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagewidget',
            name='label',
        ),
    ]
