# Generated by Django 4.0.4 on 2022-06-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0007_widget_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagewidget',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active FLAG'),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='temp',
            field=models.BooleanField(default=True, verbose_name='Temp FLAG'),
        ),
    ]
