# Generated by Django 3.2.9 on 2022-02-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0007_remove_pagewidget_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagewidget',
            name='pos',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Widget Position'),
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='thumbnail',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Widget Thumbnail'),
        ),
    ]
