# Generated by Django 3.2.9 on 2022-02-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0008_auto_20220205_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageWidget',
        ),
    ]
