# Generated by Django 3.2.9 on 2022-02-05 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0009_delete_pagewidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWidget',
            fields=[
                ('pagewidget_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Widget Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Widget Updated')),
                ('banner', models.BooleanField(default=False, verbose_name='Includes Banner Mode')),
                ('mainbody', models.BooleanField(default=True, verbose_name='Includes MainBody Mode')),
                ('sidecol', models.BooleanField(default=False, verbose_name='Includes SideColumn Mode')),
                ('footer', models.BooleanField(default=False, verbose_name='Includes Footer Mode')),
                ('pos', models.TextField(blank=True, max_length=200, null=True, verbose_name='Widget Position')),
                ('order', models.IntegerField(verbose_name='Widget Order')),
                ('thumbnail', models.TextField(blank=True, default='', null=True, verbose_name='Widget Thumbnail')),
                ('plugin_data', models.JSONField(blank=True, null=True, verbose_name='Widget plugin-specific data')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynapages.page', verbose_name='DynaPage')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynapages.widget', verbose_name='Widget')),
            ],
        ),
    ]
