# Generated by Django 4.0.4 on 2022-06-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0010_widget_app_widget_setup_form_widget_setup_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='app',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='App Name ID'),
        ),
    ]
