# Generated by Django 3.2.9 on 2022-02-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0010_pagewidget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagewidget',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Widget Order'),
        ),
    ]
