# Generated by Django 4.0.2 on 2022-02-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0011_alter_pagewidget_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagewidget',
            name='banner',
            field=models.BooleanField(default=False, verbose_name='Banner Mode'),
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='footer',
            field=models.BooleanField(default=False, verbose_name='Footer Mode'),
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='mainbody',
            field=models.BooleanField(default=False, verbose_name='MainBody Mode'),
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='pos',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Widget Position (Column)'),
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='sidecol',
            field=models.BooleanField(default=False, verbose_name='SideColumn Mode'),
        ),
    ]
