# Generated by Django 4.0.2 on 2022-02-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0012_alter_pagewidget_banner_alter_pagewidget_footer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='creator',
        ),
    ]
