# Generated by Django 4.0.2 on 2022-02-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0013_remove_templates_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='creator',
            field=models.TextField(default='system', max_length=200, verbose_name='Creator'),
        ),
    ]
