# Generated by Django 4.0.2 on 2022-02-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0014_templates_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='description',
            field=models.TextField(default='a template page', max_length=2000, verbose_name='Description'),
        ),
    ]
