# Generated by Django 4.0.2 on 2022-02-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0015_templates_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='widget_id',
            new_name='widget_uuid',
        ),
    ]
