# Generated by Django 4.0.2 on 2022-02-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0016_rename_widget_id_widget_widget_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='author',
            field=models.TextField(default='', max_length=200, verbose_name='Widget Author'),
        ),
        migrations.AddField(
            model_name='widget',
            name='widget_id',
            field=models.TextField(default='', max_length=200, verbose_name='Widget ID'),
        ),
    ]
