# Generated by Django 4.0.2 on 2022-02-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0017_widget_author_widget_widget_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='widget_id',
        ),
    ]
