# Generated by Django 4.0.2 on 2022-02-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0018_remove_widget_widget_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='widget_id',
            field=models.TextField(default='', max_length=200, verbose_name='Widget ID'),
        ),
    ]
