# Generated by Django 4.0.2 on 2022-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0019_widget_widget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='version',
            field=models.TextField(max_length='20', verbose_name='Widget Vers'),
        ),
    ]
