# Generated by Django 4.0.2 on 2022-02-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0020_alter_widget_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='widget_id',
        ),
        migrations.AddField(
            model_name='widget',
            name='widget_name',
            field=models.TextField(default='', max_length=200, unique=True, verbose_name='Widget Name'),
        ),
    ]
