# Generated by Django 4.2.4 on 2024-04-15 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galleryimagessettings",
            name="community",
        ),
        migrations.RemoveField(
            model_name="galleryimagessettings",
            name="enabled_filetypes",
        ),
        migrations.DeleteModel(
            name="GalleryImagesFileTypes",
        ),
        migrations.DeleteModel(
            name="GalleryImagesSettings",
        ),
    ]
