# Generated by Django 4.2.4 on 2024-04-15 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimagessettings",
            name="rescaler_target_format",
            field=models.OneToOneField(
                help_text="When selected, Rescaler will use this format for output. Otherwise, it will use JPEG",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="images.galleryimagesfiletypes",
                verbose_name="Rescaler output File Format",
            ),
        ),
        migrations.AddField(
            model_name="galleryimagessettings",
            name="rescaler_target_quality",
            field=models.CharField(
                help_text="(Advanced) Output File Format Specific File quality parameters - RTFM!!!!",
                null=True,
                verbose_name="Rescaler Quality Parameters",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimagessettings",
            name="rescaler_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                help_text="Rescaler Factor to use in scaling down images (default is -0.10 or -10%: i.e. decrements of 10% from the max size)",
                max_digits=4,
                verbose_name="Rescaler Factor",
            ),
        ),
    ]
