# Generated by Django 4.2.4 on 2024-04-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0004_galleryimagessettings_rescaler_target_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimagessettings",
            name="rescaler_target_quality",
            field=models.CharField(
                blank=True,
                help_text="(Advanced) Output File Format Specific File quality parameters - RTFM!!!!",
                null=True,
                verbose_name="Rescaler Quality Parameters",
            ),
        ),
    ]
