# Generated by Django 5.0.1 on 2024-05-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0005_alter_galleryimagessettings_rescaler_target_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimagessettings",
            name="enable_icc",
            field=models.BooleanField(
                default=True,
                help_text="Enable ICC Colour Profile Parsing Features",
                verbose_name="Enable ICC Parsing",
            ),
        ),
        migrations.AddField(
            model_name="galleryimagessettings",
            name="rescaler_fallback_jpeg",
            field=models.BooleanField(
                default=True,
                help_text="When advanced formats are enabled; also generate a JPEG fallback for older browsers.",
                verbose_name="Enable JPEG Fallback",
            ),
        ),
    ]
