# Generated by Django 4.0.4 on 2022-08-23 15:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_communityprofile_profile'),
        ('stats', '0002_alter_profilestat_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Name')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Icon')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('selectable', models.BooleanField(default=False, verbose_name='Selectable FLAG')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTypeStat',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('value', models.IntegerField(default=1, verbose_name='Starting Value')),
                ('classtype', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stats.classtype', verbose_name='ClassType')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.basestat', verbose_name='Stat')),
            ],
        ),
    ]
