# Generated by Django 4.0.4 on 2022-08-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_classtype_classtypestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='descr',
            field=models.TextField(default='Descr', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classtype',
            name='selectable',
            field=models.BooleanField(default=True, verbose_name='Selectable FLAG'),
        ),
    ]
