# Generated by Django 4.0.4 on 2022-08-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_classtype_descr_alter_classtype_selectable'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestat',
            name='progressable',
            field=models.BooleanField(default=True, verbose_name='Can Level up Progress FLAG'),
        ),
    ]
