# Generated by Django 4.0.4 on 2022-08-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_basestat_progressable'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestat',
            name='descr',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
