# Generated by Django 4.0.2 on 2022-04-26 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynapages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placeholder', models.BooleanField(default=False, verbose_name='Placeholder FLAG')),
                ('profile_id', models.TextField(max_length=200, unique=True, verbose_name='Profile ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Profile Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Profile Updated')),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='Profile Last Seen Online')),
                ('age', models.TextField(blank=True, default=1, verbose_name='Current Age')),
                ('name', models.TextField(verbose_name='Name')),
                ('status', models.TextField(blank=True, default='CITIZEN', verbose_name='status')),
                ('species', models.TextField(default='Sentient', verbose_name='Species')),
                ('introduction', models.TextField(verbose_name='Profile Intro')),
                ('level', models.TextField(default=1, verbose_name='Current Level')),
                ('max_HP', models.TextField(default=10, verbose_name='Max HP')),
                ('HP', models.TextField(default=10, verbose_name='Current HP')),
                ('max_MP', models.TextField(default=6, verbose_name='Max MP')),
                ('STUN', models.TextField(default=10, verbose_name='Current STUN')),
                ('max_STUN', models.TextField(default=6, verbose_name='Max STUN')),
                ('SHIELD', models.TextField(default=10, verbose_name='Current SHIELD')),
                ('max_SHIELD', models.TextField(default=6, verbose_name='Max SHIELD')),
                ('MP', models.TextField(default=6, verbose_name='Current MP')),
                ('max_STA', models.TextField(default=10, verbose_name='Max STA')),
                ('STA', models.TextField(default=10, verbose_name='Current STA')),
                ('slug', models.TextField(verbose_name='Slugified Name')),
                ('pronouns', models.TextField(max_length=200, verbose_name='Pronouns')),
                ('gender', models.TextField(max_length=200, verbose_name='Gender')),
                ('avatar', models.TextField(blank=True, null=True, verbose_name='Avatar URL')),
                ('posts', models.IntegerField(default=0, verbose_name='Post Count')),
                ('views', models.IntegerField(default=0, verbose_name='Post Count')),
                ('nodes', models.IntegerField(default=0, verbose_name='Node Count')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('dynapage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dynapages.page')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.TextField(max_length=200, verbose_name='Type ID')),
                ('label', models.TextField(max_length=200, verbose_name='Type Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Type Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Type Updated')),
                ('tickets', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ticket Count')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ticket Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Ticket Updated')),
                ('opened', models.DateTimeField(verbose_name='Ticket Initially Opened')),
                ('responded', models.DateTimeField(verbose_name='Ticket Initial Response')),
                ('notes', models.TextField(null=True, verbose_name='Ticket Notes')),
                ('reference', models.TextField(null=True, verbose_name='Ticket Reference')),
                ('contributors', models.TextField(null=True, verbose_name='Ticket Contributors')),
                ('fix', models.TextField(null=True, verbose_name='Ticket Fix')),
                ('archived', models.BooleanField(default=False, verbose_name='Ticket Archived')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='User')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.tickettype', verbose_name='Ticket Type')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('owner', models.BooleanField(default=False, verbose_name='Owner FLAG')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('public', models.BooleanField(default=True, verbose_name='Publically Viewable')),
                ('searchable', models.BooleanField(default=True, verbose_name='Show in Searches')),
                ('shareable', models.BooleanField(default=True, verbose_name='Enable Sharing')),
                ('create', models.BooleanField(default=False, verbose_name='Enable New Content Creation')),
                ('comment', models.BooleanField(default=False, verbose_name='Enable Comments on Content')),
                ('edit', models.BooleanField(default=False, verbose_name='Enable Content Editing')),
                ('delete', models.BooleanField(default=False, verbose_name='Enable Content Deletion')),
                ('nsfw', models.BooleanField(default=False, verbose_name='Enable NSFW Content Flag')),
                ('explicit', models.BooleanField(default=False, verbose_name='Enable Explicit Content Flag')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Profile')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Request Created')),
                ('approved', models.DateTimeField(null=True, verbose_name='Approved?')),
                ('approved_flag', models.BooleanField(default=False, verbose_name='Approved FLAG')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Friend 1 Profile')),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Friend 2 Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Relationship Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Dest Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile')),
            ],
        ),
    ]
