# Generated by Django 3.2.9 on 2021-11-14 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.TextField(max_length=200, verbose_name='Type ID')),
                ('label', models.TextField(max_length=200, verbose_name='Type Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Type Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Type Updated')),
                ('tickets', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ticket Count')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ticket Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Ticket Updated')),
                ('opened', models.DateTimeField(verbose_name='Ticket Initially Opened')),
                ('responded', models.DateTimeField(verbose_name='Ticket Initial Response')),
                ('notes', models.TextField(null=True, verbose_name='Ticket Notes')),
                ('reference', models.TextField(null=True, verbose_name='Ticket Reference')),
                ('contributors', models.TextField(null=True, verbose_name='Ticket Contributors')),
                ('fix', models.TextField(null=True, verbose_name='Ticket Fix')),
                ('archived', models.BooleanField(default=False, verbose_name='Ticket Archived')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='User')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.type', verbose_name='Ticket Type')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Relationship Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Dest Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile')),
            ],
        ),
    ]
