# Generated by Django 3.2.9 on 2021-11-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20211114_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='TicketType',
        ),
    ]
