# Generated by Django 3.2.9 on 2021-11-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_type_tickettype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
    ]
