# Generated by Django 3.2.9 on 2021-11-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupkeywords'),
        ('profiles', '0006_auto_20211114_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('owner', models.BooleanField(default=False, verbose_name='Owner FLAG')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('public', models.BooleanField(default=True, verbose_name='Publically Viewable')),
                ('searchable', models.BooleanField(default=True, verbose_name='Show in Searches')),
                ('shareable', models.BooleanField(default=True, verbose_name='Enable Sharing')),
                ('create', models.BooleanField(default=False, verbose_name='Enable New Content Creation')),
                ('comment', models.BooleanField(default=False, verbose_name='Enable Comments on Content')),
                ('edit', models.BooleanField(default=False, verbose_name='Enable Content Editing')),
                ('delete', models.BooleanField(default=False, verbose_name='Enable Content Deletion')),
                ('nsfw', models.BooleanField(default=False, verbose_name='Enable NSFW Content Flag')),
                ('explicit', models.BooleanField(default=False, verbose_name='Enable Explicit Content Flag')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Profile')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Visitor')),
            ],
        ),
    ]
