# Generated by Django 4.0.4 on 2022-08-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0011_templates_app'),
        ('profiles', '0006_remove_profile_dashboard dynapage node'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePageNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.TextField(null=True, verbose_name='Dynapage Node Type')),
                ('dynapage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dynapages.page', verbose_name='DynaPage Node/Page')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile')),
            ],
        ),
    ]
