# Generated by Django 3.2.9 on 2021-11-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupkeywords'),
        ('profiles', '0007_profilepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepermission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group'),
        ),
    ]
