# Generated by Django 3.2.9 on 2021-11-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profilepermission_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='Avatar URL'),
        ),
    ]
