# Generated by Django 3.2.9 on 2021-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.TextField(default='', verbose_name='Slugified Name'),
            preserve_default=False,
        ),
    ]
