# Generated by Django 3.2.9 on 2022-02-03 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0001_initial'),
        ('profiles', '0013_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dynapage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dynapages.page'),
        ),
    ]
