# Generated by Django 4.0.2 on 2022-02-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_dynapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(default='', max_length=200, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
