# Generated by Django 4.0.2 on 2022-02-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_tagline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tagline',
            new_name='introduction',
        ),
    ]
