# Generated by Django 4.0.2 on 2022-02-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_rename_tagline_profile_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='introduction',
        ),
        migrations.AddField(
            model_name='profile',
            name='HP',
            field=models.TextField(default=10, verbose_name='Current HP'),
        ),
        migrations.AddField(
            model_name='profile',
            name='STA',
            field=models.TextField(default=6, verbose_name='Current MP'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.TextField(default=1, verbose_name='Current Level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_HP',
            field=models.TextField(default=10, verbose_name='Max HP'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_STA',
            field=models.TextField(default=6, verbose_name='Max MP'),
        ),
    ]
