# Generated by Django 4.0.2 on 2022-02-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_remove_profile_introduction_profile_hp_profile_sta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.TextField(default='', verbose_name='Profile Intro'),
            preserve_default=False,
        ),
    ]
