# Generated by Django 4.0.2 on 2022-02-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_profile_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='MP',
            field=models.TextField(default=6, verbose_name='Current MP'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_MP',
            field=models.TextField(default=6, verbose_name='Max MP'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='STA',
            field=models.TextField(default=6, verbose_name='Current STA'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_STA',
            field=models.TextField(default=6, verbose_name='Max STA'),
        ),
    ]
