# Generated by Django 4.0.2 on 2022-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_profile_mp_profile_max_mp_alter_profile_sta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='STA',
            field=models.TextField(default=10, verbose_name='Current STA'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_STA',
            field=models.TextField(default=10, verbose_name='Max STA'),
        ),
    ]
