# Generated by Django 4.0.2 on 2022-02-11 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_profile_sta_alter_profile_max_sta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.TextField(default=1, verbose_name='Current Age'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Profile Last Seen Online'),
            preserve_default=False,
        ),
    ]
