# Generated by Django 4.0.2 on 2022-02-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_profile_age_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='species',
            field=models.TextField(default='Sentient', verbose_name='Species'),
            preserve_default=False,
        ),
    ]
