# Generated by Django 4.0.2 on 2022-02-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_profile_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='species',
            field=models.TextField(default='Sentient', verbose_name='Species'),
        ),
    ]
