# Generated by Django 4.0.2 on 2022-02-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_profile_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.TextField(default='CITIZEN', verbose_name='status'),
        ),
    ]
