# Generated by Django 4.0.2 on 2022-02-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='placeholder',
            field=models.BooleanField(default=False, verbose_name='Placeholder FLAG'),
        ),
    ]
