# Generated by Django 4.0.2 on 2022-02-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_profile_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='source',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.TextField(blank=True, default=1, verbose_name='Current Age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.TextField(max_length=200, unique=True, verbose_name='Profile ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.TextField(blank=True, default='CITIZEN', verbose_name='status'),
        ),
    ]
