# Generated by Django 4.0.2 on 2022-02-18 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_remove_follower_dest_remove_follower_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend1',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend2',
        ),
        migrations.AddField(
            model_name='follower',
            name='dest',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Dest Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile'),
            preserve_default=False,
        ),
    ]
