# Generated by Django 4.0.2 on 2022-02-18 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_remove_friend_friend1_remove_friend_friend2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Friend 1 Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='friend2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Friend 2 Profile'),
            preserve_default=False,
        ),
    ]
