# Generated by Django 4.0.2 on 2022-02-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_friend_friend1_friend_friend2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='profile',
        ),
    ]
