# Generated by Django 4.0.2 on 2022-02-18 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_remove_ticket_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepermission',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profilepermission',
            name='visitor',
        ),
        migrations.AddField(
            model_name='ticket',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='User'),
        ),
    ]
