# Generated by Django 4.0.2 on 2022-02-18 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_remove_profilepermission_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepermission',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilepermission',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Visitor'),
        ),
    ]
