# Generated by Django 4.0.4 on 2023-04-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone #')),
                ('addr1', models.CharField(max_length=100, verbose_name='Address Line 1')),
                ('addr2', models.CharField(max_length=100, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=10, verbose_name='State/Province')),
                ('zip', models.CharField(max_length=10, verbose_name='Address Zip/Post Code')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
    ]
