# Generated by Django 4.2.4 on 2023-11-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_alter_registrationloot_stripe_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrantlootfulfillment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='registrantlootfulfillment',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Item Count'),
        ),
    ]
