# Generated by Django 4.0.4 on 2023-04-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_registrant_created_registrant_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrantLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.TextField(max_length=200, verbose_name='Level ID')),
                ('label', models.TextField(max_length=200, verbose_name='Level Label')),
            ],
        ),
        migrations.AddField(
            model_name='registrant',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='registrar.registrantlevel', verbose_name='Registrant Level'),
            preserve_default=False,
        ),
    ]
