# Generated by Django 4.2.4 on 2023-11-16 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_remove_registrantlootfulfillment_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='registrar.event', verbose_name='Registrant Event:'),
        ),
    ]
