# Generated by Django 4.2.4 on 2023-11-16 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('registrar', '0004_registrant_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Select profile: '),
        ),
        migrations.AlterField(
            model_name='registrantlootfulfillment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Fulfilment Request Active'),
        ),
        migrations.AlterField(
            model_name='registrantlootfulfillment',
            name='fulfilled',
            field=models.BooleanField(default=False, verbose_name='Request Complete'),
        ),
    ]
