# Generated by Django 4.0.4 on 2023-04-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0004_registrant_fd_donation_registrant_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrant',
            old_name='fd_donation',
            new_name='fdDonation',
        ),
        migrations.AddField(
            model_name='registrant',
            name='chDonation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Charity Donation'),
        ),
    ]
