# Generated by Django 4.2.4 on 2023-11-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0005_alter_registrant_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrantdata',
            name='conRegLevel',
        ),
    ]
