# Generated by Django 4.0.4 on 2023-04-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0005_rename_fd_donation_registrant_fddonation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='agreeCOC',
            field=models.BooleanField(default=False, verbose_name='Agree to Code of Conduct'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='agreeCOCDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agreed to Code of Conduct Date'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='agreeCVD',
            field=models.BooleanField(default=False, verbose_name='Agree to COVID Policy'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='agreeCVDDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agreed to COVID Policy Date'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='agreeRFP',
            field=models.BooleanField(default=False, verbose_name='Agree to Refund Policy'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='agreeRFPDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agreed to Refund Policy Date'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='badgeName',
            field=models.CharField(default='', max_length=100, verbose_name='Badge Name'),
            preserve_default=False,
        ),
    ]
