# Generated by Django 4.2.4 on 2023-11-20 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0006_remove_registrantdata_conreglevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantdata',
            name='conRegLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrar.registrantlevel'),
        ),
    ]
