# Generated by Django 4.0.4 on 2023-04-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0006_registrant_agreecoc_registrant_agreecocdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='outstandingAmount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='paidDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
