# Generated by Django 4.0.4 on 2023-04-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0007_registrant_amount_registrant_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='outstandingAmount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outstanding Amount'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total'),
        ),
    ]
