# Generated by Django 4.2.4 on 2023-11-21 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('registrar', '0008_remove_registrantdata_croppedimage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventcommunitymapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventcommunitymapping',
            name='community',
        ),
        migrations.RemoveField(
            model_name='eventcommunitymapping',
            name='event',
        ),
        migrations.AddField(
            model_name='registrantlevel',
            name='day_pass',
            field=models.BooleanField(default=True, verbose_name='Day Pass Flag'),
        ),
        migrations.AddField(
            model_name='registrantlevel',
            name='minor',
            field=models.BooleanField(default=True, verbose_name='Minor Flag'),
        ),
        migrations.AlterField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='event.event', verbose_name='Registrant Event:'),
        ),
        migrations.AlterField(
            model_name='registrantdata',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.event'),
        ),
        migrations.AlterField(
            model_name='registrantlevel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='registrantlootfulfillment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='registrationlevelloot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='registrationloot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.DeleteModel(
            name='ConBadgeLevelMap',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventCommunityMapping',
        ),
    ]
