# Generated by Django 4.0.4 on 2023-04-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0008_alter_registrant_amount_alter_registrant_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='country',
            field=models.CharField(default='USA', max_length=100, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
