# Generated by Django 4.0.4 on 2023-04-30 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furry', '0011_registrantassociationkey'),
        ('registrar', '0009_registrant_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='addr1',
            field=models.CharField(max_length=100, verbose_name='Address Line 1: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='addr2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address Line 2: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='agreeCOC',
            field=models.BooleanField(default=False, verbose_name='Agreed to Code of Conduct'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='agreeCVD',
            field=models.BooleanField(default=False, verbose_name=' Agreed to the COVID Policy'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='agreeRFP',
            field=models.BooleanField(default=False, verbose_name=' Agreed Refund Policy'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='badgeName',
            field=models.CharField(max_length=100, verbose_name='Badge Name: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='chDonation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Charity Donation: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='fdDonation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Furrydelphia Donation: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='First Name: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Last Name: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registrar.registrantlevel', verbose_name='Registrant Level: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone #: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='furry.profile', verbose_name='Registrant Profile: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='state',
            field=models.CharField(max_length=10, verbose_name='State/Province: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated: '),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='zip',
            field=models.CharField(max_length=10, verbose_name='Address Zip/Post Code: '),
        ),
    ]
