# Generated by Django 4.0.4 on 2023-04-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0011_remove_registrant_id_registrant_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantlevel',
            name='cost',
            field=models.IntegerField(default=65, verbose_name='Cost'),
        ),
    ]
