# Generated by Django 4.0.4 on 2023-05-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0012_registrantlevel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantlevel',
            name='stripe_price',
            field=models.TextField(default='', max_length=200, verbose_name='Level Stripe Price ID'),
            preserve_default=False,
        ),
    ]
