# Generated by Django 4.0.4 on 2023-05-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0013_registrantlevel_stripe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantlevel',
            name='stripe_price_test',
            field=models.TextField(default='', max_length=200, verbose_name='Level Stripe Test Price ID'),
            preserve_default=False,
        ),
    ]
