# Generated by Django 4.0.4 on 2022-08-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyscript', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='body',
            field=models.TextField(verbose_name='Script Body'),
        ),
    ]
