# Generated by Django 4.0.4 on 2022-08-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyscript', '0002_alter_script_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='function_name',
            field=models.CharField(max_length=1000, verbose_name='Script Funcname'),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Script Name'),
        ),
        migrations.AlterField(
            model_name='script',
            name='type',
            field=models.CharField(default='application/ply.script.generic', max_length=100, verbose_name='Script Type'),
        ),
    ]
