# Generated by Django 4.0.4 on 2022-08-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyscript', '0003_alter_script_function_name_alter_script_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='script',
            constraint=models.UniqueConstraint(fields=('community', 'function_name'), name='unique_funcname'),
        ),
        migrations.AddConstraint(
            model_name='script',
            constraint=models.UniqueConstraint(fields=('community', 'name'), name='unique_name'),
        ),
    ]
