# Generated by Django 4.0.4 on 2022-08-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plyscript', '0005_scriptregistry_scriptregistry_unique_keyperpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='function_name',
            field=models.CharField(max_length=1000, verbose_name='Script Function/Callable Name (no spaces)'),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Script Human-readable name'),
        ),
    ]
