# Generated by Django 3.1.7 on 2021-05-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allowedDomain',
            field=models.CharField(default='marketplace.furrydelphia.org', help_text='Domain used to validate access in Userland', max_length=500),
            preserve_default=False,
        ),
    ]
