# Generated by Django 3.2.4 on 2022-03-20 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_statusmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('email', models.EmailField(max_length=254)),
                ('reservation', models.JSONField(blank=True, null=True)),
                ('group', models.CharField(choices=[('Super Sponsors', 'Super Sponsors'), ('Dealers', 'Dealers'), ('Elite Sponsors', 'Elite Sponsors'), ('Staff', 'Staff')], max_length=100)),
            ],
        ),
    ]
