# Generated by Django 3.2.4 on 2022-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_reservationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationkey',
            name='group',
            field=models.CharField(choices=[('Super Sponsors', 'Super Sponsors'), ('Dealers', 'Dealers'), ('Elite Sponsors', 'Elite Sponsors'), ('Staff', 'Staff'), ('Contractor', 'Contractor'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reservationkey',
            name='reservation',
            field=models.JSONField(default={}),
        ),
    ]
