# Generated by Django 3.2.4 on 2022-04-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_alter_reservationkey_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationkey',
            name='group',
            field=models.CharField(choices=[('Dealers', 'Dealers'), ('Attendee Sponsors', 'Attendee Sponsors'), ('Staff', 'Staff'), ('Contractor', 'Contractor'), ('Other', 'Other')], max_length=100),
        ),
    ]
