# Generated by Django 3.2.4 on 2022-04-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_alter_reservationkey_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationkey',
            name='sent',
            field=models.BooleanField(default=False, help_text='Have we sent them an e-mail yet?'),
        ),
    ]
