# Generated by Django 4.2.4 on 2023-08-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_reservationkey_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='staff_only',
            field=models.BooleanField(default=False, help_text='Only staff can access this application'),
        ),
    ]
