# Generated by Django 4.2.4 on 2023-08-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0009_application_staff_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='show_on_app_list',
            field=models.BooleanField(default=False, help_text='Show this application on the application list'),
        ),
    ]
