# Generated by Django 4.0.4 on 2022-05-23 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_friend_community'),
        ('SLHUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLParcel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Agent First seen')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('online', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
            ],
        ),
    ]
