# Generated by Django 4.0.4 on 2022-05-23 18:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SLHUD', '0002_slparcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slagent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slparcel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SLParcelAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='Agent Last seen')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Agent UUID')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('online', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHUD.slparcel', verbose_name='Parcel')),
            ],
        ),
        migrations.AddIndex(
            model_name='slparcelagent',
            index=models.Index(fields=['uuid'], name='SLHUD_slpar_uuid_8804f4_idx'),
        ),
    ]
