# Generated by Django 4.0.4 on 2022-07-07 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_mentions_profile_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SLHUD', '0004_slparcelagent_active_alter_slparcelagent_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='slagent',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='slagent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Character Profile'),
        ),
    ]
