# Generated by Django 4.0.4 on 2022-07-08 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_friend_community'),
        ('SLHUD', '0005_slagent_owner_alter_slagent_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLHUDSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Settings Created/updated')),
                ('hud_title', models.TextField(max_length=200, unique=True, verbose_name='HUD Title (World Name)')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('online', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
            ],
        ),
    ]
