# Generated by Django 4.0.4 on 2022-07-08 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_mentions_profile_messages'),
        ('SLHUD', '0007_slhudsettings_hud_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='slhudsettings',
            name='max_profiles',
            field=models.IntegerField(default=3, verbose_name='Max Profiles Allowed'),
        ),
        migrations.AlterField(
            model_name='slagent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Active Character Profile'),
        ),
    ]
