# Generated by Django 4.0.4 on 2022-05-31 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Preferences Node Updated')),
                ('shortdate', models.TextField(default='%x', verbose_name='Short Datetime Format for Output')),
                ('longdate', models.TextField(default='%c', verbose_name='Long Date Format for Output')),
                ('timezone', models.TextField(default='America/New_York', verbose_name='TimeZone Code')),
                ('theme', models.TextField(default='Default', verbose_name='System Theme')),
                ('time', models.TextField(default='%I:%M:%S', verbose_name='Time Format for Output')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
