# Generated by Django 4.2.4 on 2023-08-15 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.TextField(default='default', verbose_name='Theme ID')),
                ('name', models.TextField(default='Ply Default Theme', verbose_name='Theme Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'communities_preferences_theme',
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tz', models.TextField(default='America/New_York', verbose_name='TimeZone Code')),
                ('timezone', models.TextField(default='America/New_York', verbose_name='TimeZone Name')),
                ('offset', models.TextField(default='-05:00', verbose_name='TimeZone Code')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'communities_preferences_timezone',
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Preferences Node Updated')),
                ('shortdate', models.TextField(default='%x', max_length=50, verbose_name='Short Date  Format for Output')),
                ('shortdatetime', models.TextField(default='%x %X', max_length=50, verbose_name='Short Date+Time Format for Output')),
                ('longdate', models.TextField(default='%c', max_length=50, verbose_name='Long Date Format for Output')),
                ('time', models.TextField(default='%I:%M:%S', max_length=50, verbose_name='Time Format for Output')),
                ('stream_top', models.BooleanField(default=False, verbose_name='Scroll Streams Top-Down')),
                ('messages_top', models.BooleanField(default=False, verbose_name='Scroll Messages Top-Down')),
                ('min_zoom', models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='Gallery Min Zoom (Default value is 0.1)')),
                ('max_zoom', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Gallery Abs Max Zoom (Default value is 10)')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='preferences.theme', verbose_name='System Theme')),
                ('timezone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='preferences.timezone', verbose_name='TimeZone Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'communities_preferences_preferences',
            },
        ),
    ]
