# Generated by Django 4.0.4 on 2022-05-31 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tz', models.TextField(default='America/New_York', verbose_name='TimeZone Code')),
                ('timezone', models.TextField(default='America/New_York', verbose_name='TimeZone Name')),
                ('offset', models.TextField(default='America/New_York', verbose_name='TimeZone Code')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.AddField(
            model_name='preferences',
            name='messages_top',
            field=models.BooleanField(default=False, verbose_name='Scroll Messages Top-Down'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='stream_top',
            field=models.BooleanField(default=False, verbose_name='Scroll Streams Top-Down'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='shortdate',
            field=models.TextField(default='%x', verbose_name='Short Date Time Format for Output'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='timezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='preferences.timezone', verbose_name='TimeZone Code'),
        ),
    ]
