# Generated by Django 4.0.4 on 2022-08-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0006_alter_preferences_longdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='max_zoom',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Gallery Abs Max Zoom (Default value is 10)'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='min_zoom',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='Gallery Min Zoom (Default value is 0.1)'),
        ),
    ]
