# Generated by Django 4.0.4 on 2022-08-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0007_preferences_max_zoom_preferences_min_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='shortdatetime',
            field=models.TextField(default='%x %X', max_length=50, verbose_name='Short Date+Time Format for Output'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='shortdate',
            field=models.TextField(default='%x', max_length=50, verbose_name='Short Date  Format for Output'),
        ),
    ]
