# Generated by Django 3.2.9 on 2021-11-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryArtworkCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.TextField(max_length=200, verbose_name='Type ID')),
                ('label', models.TextField(max_length=200, verbose_name='Type Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Type Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Type Updated')),
                ('items', models.IntegerField(blank=True, default=0, null=True, verbose_name='Item Count')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCatGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.TextField(max_length=200, verbose_name='Group ID')),
                ('label', models.TextField(max_length=200, verbose_name='Group Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Group Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Group Updated')),
                ('items', models.IntegerField(blank=True, default=0, null=True, verbose_name='Item Count')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.TextField(max_length=200, verbose_name='Type ID')),
                ('label', models.TextField(max_length=200, verbose_name='Type Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Type Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Type Updated')),
                ('items', models.IntegerField(blank=True, default=0, null=True, verbose_name='Item Count')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCatGroupObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryartworkcat', verbose_name='Gallery Category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycatgroups', verbose_name='Gallery Category Parent Group')),
            ],
        ),
    ]
