# Generated by Django 3.2.9 on 2021-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.TextField(max_length=200, verbose_name='Type ID')),
                ('label', models.TextField(max_length=200, verbose_name='Type Label')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Type Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Type Updated')),
                ('items', models.IntegerField(default=0, verbose_name='Item Count')),
                ('views', models.IntegerField(default=0, verbose_name='Views Count')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes Count')),
                ('shares', models.IntegerField(default=0, verbose_name='Shares Count')),
                ('comments', models.IntegerField(default=0, verbose_name='Comment Count')),
            ],
        ),
    ]
