# Generated by Django 4.0.2 on 2022-05-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryTempFileThumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, null=True, verbose_name='File Path')),
                ('file_size', models.FloatField(default=0, verbose_name='File Size')),
                ('order', models.IntegerField(default=0, verbose_name='Order Column')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerytempfile', verbose_name='Item')),
            ],
        ),
    ]
