# Generated by Django 3.2.9 on 2021-11-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerycollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItemTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.TextField(max_length=200, verbose_name='Type ID')),
                ('label', models.TextField(max_length=200, verbose_name='Type Label')),
                ('mimetypes', models.TextField(verbose_name='Type Mimetypes')),
                ('service', models.TextField(max_length=200, verbose_name='Type Service Provider')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Type Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Type Updated')),
                ('items', models.IntegerField(blank=True, default=0, null=True, verbose_name='Item Count')),
            ],
        ),
        migrations.RemoveField(
            model_name='galleryartworkcat',
            name='type_id',
        ),
        migrations.AddField(
            model_name='galleryartworkcat',
            name='cat_id',
            field=models.TextField(default='', max_length=200, verbose_name='Cat ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryartworkcat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cat Created'),
        ),
        migrations.AlterField(
            model_name='galleryartworkcat',
            name='label',
            field=models.TextField(max_length=200, verbose_name='Cat Label'),
        ),
        migrations.AlterField(
            model_name='galleryartworkcat',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Cat Updated'),
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_hash', models.TextField(max_length=200, verbose_name='Item Hash')),
                ('title', models.TextField(max_length=200, verbose_name='Item Title')),
                ('descr', models.TextField(max_length=200, verbose_name='Item Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Item Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='tem Updated')),
                ('files', models.IntegerField(default=0, verbose_name='Item Count')),
                ('views', models.IntegerField(default=0, verbose_name='Views Count')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes Count')),
                ('shares', models.IntegerField(default=0, verbose_name='Shares Count')),
                ('comments', models.IntegerField(default=0, verbose_name='Comment Count')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gallery.galleryitemtypes', verbose_name='Item Type')),
            ],
        ),
    ]
