# Generated by Django 4.0.4 on 2022-06-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallerytempfilethumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitemcategory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem', verbose_name='Item'),
        ),
    ]
