# Generated by Django 3.2.9 on 2021-11-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20211114_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='File Name')),
                ('hash', models.TextField(verbose_name='File Hash')),
                ('data', models.TextField(verbose_name='File Data')),
                ('meta', models.TextField(verbose_name='File Metadata')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCollectionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order Column')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycollection', verbose_name='Collection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem', verbose_name='Item')),
            ],
        ),
    ]
