# Generated by Django 3.2.9 on 2021-11-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_type_tickettype'),
        ('gallery', '0005_auto_20211114_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItemComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('order', models.IntegerField(default=0, verbose_name='Order Column')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('flagged', models.BooleanField(default=False, verbose_name='FLAGGED')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gallery.galleryitem', verbose_name='Item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Item')),
            ],
        ),
    ]
