# Generated by Django 4.0.4 on 2022-06-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_rename_category_galleryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='en_comments',
            field=models.BooleanField(default=True, verbose_name='Item Comments Enabled Flag'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='en_download',
            field=models.BooleanField(default=True, verbose_name='Item Download Enabled Flag'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='en_sharing',
            field=models.BooleanField(default=True, verbose_name='Item Sharing Enabled Flag'),
        ),
    ]
