# Generated by Django 3.2.9 on 2021-11-14 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_type_tickettype'),
        ('gallery', '0006_galleryitemcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='explicit',
            field=models.BooleanField(default=False, verbose_name='Item Explicit'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='nsfw',
            field=models.BooleanField(default=False, verbose_name='Item NSFW Flag'),
        ),
        migrations.CreateModel(
            name='GalleryCollectionPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('owner', models.BooleanField(default=False, verbose_name='Owner FLAG')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('public', models.BooleanField(default=True, verbose_name='Publically Viewable')),
                ('searchable', models.BooleanField(default=True, verbose_name='Show in Searches')),
                ('shareable', models.BooleanField(default=True, verbose_name='Enable Sharing')),
                ('create', models.BooleanField(default=False, verbose_name='Enable New Content Creation')),
                ('edit', models.BooleanField(default=False, verbose_name='Enable Content Editing')),
                ('delete', models.BooleanField(default=False, verbose_name='Enable Content Deletion')),
                ('nsfw', models.BooleanField(default=False, verbose_name='Enable NSFW Content Flag')),
                ('explicit', models.BooleanField(default=False, verbose_name='Enable Explicit Content Flag')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycollection', verbose_name='Gallery Collection')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Item')),
            ],
        ),
    ]
