# Generated by Django 4.0.4 on 2022-06-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_galleryitem_en_comments_galleryitem_en_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='detail_style',
            field=models.TextField(default='b', verbose_name='Item Detail Style'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='display_details',
            field=models.TextField(default='t', verbose_name='Item Display Details'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='sizing_hint',
            field=models.TextField(default='1', verbose_name='Item Sizing Hint'),
        ),
    ]
