# Generated by Django 3.2.9 on 2021-11-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('gallery', '0007_auto_20211114_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitemkeywords',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='keywords.keyword', verbose_name='keyword'),
        ),
        migrations.DeleteModel(
            name='GalleryKeyword',
        ),
    ]
