# Generated by Django 3.2.9 on 2021-11-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupkeywords'),
        ('gallery', '0008_auto_20211114_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycollectionpermissions',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Item'),
        ),
    ]
