# Generated by Django 3.2.9 on 2021-11-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_gallerycollectionpermissions_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycollectionpermissions',
            name='comment',
            field=models.BooleanField(default=False, verbose_name='Enable Comments on Content'),
        ),
    ]
