# Generated by Django 4.0.4 on 2022-08-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_galleryfavourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItemsByFavourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gci_title', models.CharField(max_length=200, verbose_name='Gallery Item Title')),
                ('gci_descr', models.CharField(max_length=200, verbose_name='Gallery Item Description')),
                ('gci_details', models.CharField(max_length=200, verbose_name='Gallery Item Details Style')),
                ('gci_hash', models.CharField(max_length=200, verbose_name='Gallery Item Hash')),
                ('gci_created', models.DateTimeField(verbose_name='Gallery Item Created')),
                ('gci_updated', models.DateTimeField(verbose_name='Gallery Item Updated')),
                ('gci_files', models.IntegerField(verbose_name='Gallery Item Files')),
                ('gci_views', models.IntegerField(verbose_name='Gallery Item Views')),
                ('gci_likes', models.IntegerField(verbose_name='Gallery Item Likes')),
                ('gci_shares', models.IntegerField(verbose_name='Gallery Item Shares')),
                ('gci_comments', models.IntegerField(verbose_name='Gallery Item Comments')),
                ('gci_nsfw', models.BooleanField(verbose_name='Collection Item: NSFW?')),
                ('gci_plugin', models.JSONField(verbose_name='Gallery Item Plguin')),
                ('gci_plugin_data', models.JSONField(verbose_name='Gallery Item Plguin JSON Data')),
                ('gci_thumbnail', models.BooleanField(verbose_name='Collection Item: Thumbnail?')),
                ('gci_processed', models.BooleanField(verbose_name='Collection Item: Processed?')),
                ('gci_uuid', models.UUIDField(verbose_name='Gallery Item UUID')),
                ('gci_configured', models.BooleanField(verbose_name='Gallery Item Configured')),
                ('gci_active', models.BooleanField(verbose_name='Gallery Item Active')),
                ('gci_archived', models.BooleanField(verbose_name='Gallery Item Archived')),
                ('gci_frozen', models.BooleanField(verbose_name='Gallery Item Frozen')),
                ('gci_downloads', models.BooleanField(verbose_name='Gallery Item Downloads')),
                ('gci_sizing', models.IntegerField(verbose_name='Gallery Item Sizing')),
                ('gci_style', models.CharField(max_length=200, verbose_name='Gallery Item Style')),
                ('gci_rating', models.CharField(max_length=200, verbose_name='Gallery Item Rating')),
                ('gif_name', models.CharField(max_length=200, verbose_name='Gallery File Name')),
                ('gif_id', models.IntegerField(verbose_name='Gallery File ID')),
                ('gif_data', models.CharField(max_length=200, verbose_name='Gallery File Data')),
                ('gif_created', models.DateTimeField(verbose_name='Gallery File Created')),
                ('gif_updated', models.DateTimeField(verbose_name='Gallery File Updated')),
                ('gif_meta', models.JSONField(verbose_name='Gallery File Metadata')),
                ('gif_bindata', models.BinaryField(verbose_name='Gallery File Binary Data')),
                ('gif_jsondata', models.JSONField(verbose_name='Gallery File Json data')),
                ('gif_thumbnail', models.BooleanField(verbose_name='Gallery File: is thumbnail?')),
                ('gif_size', models.IntegerField(verbose_name='Gallery File Size')),
                ('gif_type', models.CharField(max_length=200, verbose_name='Gallery File Type')),
                ('gif_original', models.BooleanField(verbose_name='Gallery File: Original?')),
                ('gif_item', models.UUIDField(verbose_name='Gallery File Item UUID')),
                ('gif_profile', models.UUIDField(verbose_name='Gallery Favorite Profile UUID')),
                ('gc_uuid', models.UUIDField(verbose_name='Gallery Collection UUID')),
                ('collection_id', models.UUIDField(verbose_name='Gallery Collection UUID')),
                ('gal_path', models.CharField(max_length=200, verbose_name='Gallery Path')),
                ('profile_name', models.CharField(max_length=200, verbose_name='Profile Name')),
                ('profile_pronouns', models.CharField(max_length=200, verbose_name='Profile Pronouns')),
                ('profile_avatar', models.CharField(max_length=200, verbose_name='Profile Avtar')),
                ('profile_slug', models.CharField(max_length=200, verbose_name='Profile Slug')),
                ('profile_uuid', models.CharField(max_length=200, verbose_name='Profile UUID')),
            ],
            options={
                'db_table': 'gallery_itemsbyfavouriteview',
                'managed': False,
            },
        ),
        migrations.AddConstraint(
            model_name='galleryfavourite',
            constraint=models.UniqueConstraint(fields=('item', 'profile'), name='unique_favourite'),
        ),
    ]
