# Generated by Django 3.2.9 on 2021-11-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupkeywords'),
        ('profiles', '0006_auto_20211114_1904'),
        ('gallery', '0010_gallerycollectionpermissions_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryCollectionPermissions',
            new_name='GalleryCollectionPermission',
        ),
    ]
