# Generated by Django 4.0.4 on 2022-08-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_galleryitemsbyfavourites_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='galleryfavourite',
            name='unique_favourite',
        ),
        migrations.AddConstraint(
            model_name='galleryfavourite',
            constraint=models.UniqueConstraint(fields=('item', 'profile', 'community'), name='unique_favourite'),
        ),
    ]
