# Generated by Django 3.2.9 on 2021-11-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('gallery', '0011_rename_gallerycollectionpermissions_gallerycollectionpermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryItemKeywords',
            new_name='GalleryItemKeyword',
        ),
    ]
