# Generated by Django 3.2.9 on 2021-11-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_rename_galleryitemkeywords_galleryitemkeyword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryCatGroupObjects',
            new_name='GalleryCatGroupObject',
        ),
    ]
