# Generated by Django 3.2.9 on 2021-11-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profilepermission'),
        ('group', '0002_groupkeywords'),
        ('gallery', '0013_rename_gallerycatgroupobjects_gallerycatgroupobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitemfile',
            old_name='meta',
            new_name='_meta',
        ),
        migrations.AlterField(
            model_name='gallerycollectionpermission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='gallerycollectionpermission',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile'),
        ),
    ]
