# Generated by Django 3.2.9 on 2021-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20211114_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitemfile',
            name='_meta',
        ),
        migrations.AddField(
            model_name='galleryitemfile',
            name='meta_new',
            field=models.JSONField(default='', verbose_name='File Metadata'),
            preserve_default=False,
        ),
    ]
