# Generated by Django 3.2.9 on 2021-11-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20211114_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitemfile',
            old_name='meta_new',
            new_name='meta',
        ),
    ]
