# Generated by Django 3.2.9 on 2021-11-17 01:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_rename_meta_new_galleryitemfile_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='id',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='plugin',
            field=models.TextField(default='', null=True, verbose_name='Item Plugin'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='plugin_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Item plugin-specific data'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Item has been processed'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='temp_file',
            field=models.TextField(default='', null=True, verbose_name='Item Temporary file for ingestion'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='thumbnail',
            field=models.TextField(default='', null=True, verbose_name='Item Thumbnail'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
