# Generated by Django 3.2.9 on 2021-11-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_auto_20211117_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='temp_file_name',
            field=models.TextField(default='', null=True, verbose_name='Item Temporary file name from ingestion'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='temp_file',
            field=models.TextField(default='', null=True, verbose_name='Item Temporary file from ingestion'),
        ),
    ]
