# Generated by Django 3.2.9 on 2021-11-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_auto_20211117_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='configured',
            field=models.BooleanField(default=False, verbose_name='Item has been configured (pre-processing)'),
        ),
    ]
