# Generated by Django 3.2.9 on 2021-11-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_galleryitem_configured'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Item Active Flag'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Item Archived Flag'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='frozen',
            field=models.BooleanField(default=False, verbose_name='Item Frozen Flag'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Item Hidden Flag'),
        ),
    ]
