# Generated by Django 3.2.9 on 2021-11-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_auto_20211117_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitemfile',
            name='bindata',
            field=models.BinaryField(blank=True, verbose_name='File Bindata'),
        ),
        migrations.AddField(
            model_name='galleryitemfile',
            name='jsondata',
            field=models.JSONField(blank=True, default='', verbose_name='File JSONData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryitemfile',
            name='thumbnail',
            field=models.BooleanField(default=False, verbose_name='File is a thumbnail'),
        ),
        migrations.AlterField(
            model_name='galleryitemfile',
            name='data',
            field=models.TextField(blank=True, verbose_name='File Data'),
        ),
    ]
