# Generated by Django 3.2.9 on 2021-11-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_auto_20211117_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitemfile',
            name='bindata',
            field=models.BinaryField(blank=True, null=True, verbose_name='File Bindata'),
        ),
        migrations.AlterField(
            model_name='galleryitemfile',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='File Data'),
        ),
        migrations.AlterField(
            model_name='galleryitemfile',
            name='jsondata',
            field=models.JSONField(blank=True, null=True, verbose_name='File JSONData'),
        ),
    ]
