# Generated by Django 3.2.9 on 2021-11-17 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('profiles', '0010_profile_slug'),
        ('gallery', '0022_auto_20211117_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryTempFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='File Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('type', models.TextField(verbose_name='File Type')),
                ('path', models.TextField(blank=True, null=True, verbose_name='File Path')),
                ('data', models.TextField(blank=True, null=True, verbose_name='File Text Data')),
                ('bindata', models.BinaryField(blank=True, null=True, verbose_name='File Bindata')),
                ('jsondata', models.JSONField(blank=True, null=True, verbose_name='File JSONData')),
                ('meta', models.JSONField(verbose_name='File Metadata')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='gallerycollection',
            name='id',
        ),
        migrations.AddField(
            model_name='gallerycollection',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallerycollection',
            name='collection_id',
            field=models.TextField(max_length=200, verbose_name='Collection ID'),
        ),
        migrations.AlterField(
            model_name='gallerycollection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Collection Created'),
        ),
        migrations.AlterField(
            model_name='gallerycollection',
            name='label',
            field=models.TextField(max_length=200, verbose_name='Collection Label'),
        ),
        migrations.AlterField(
            model_name='gallerycollection',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Collection Updated'),
        ),
        migrations.CreateModel(
            name='GalleryTempFileKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order Column')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerytempfile', verbose_name='Temp File')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.keyword', verbose_name='keyword')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryTempFileCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order Column')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycollection', verbose_name='Collection')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerytempfile', verbose_name='Item')),
            ],
        ),
    ]
