# Generated by Django 3.2.9 on 2021-11-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0023_auto_20211117_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitemfile',
            name='file_size',
            field=models.FloatField(default=0, verbose_name='File Size'),
        ),
        migrations.AddField(
            model_name='galleryitemfile',
            name='type',
            field=models.TextField(default='', verbose_name='File Type'),
            preserve_default=False,
        ),
    ]
