# Generated by Django 3.2.9 on 2021-11-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_auto_20211118_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='downloads',
            field=models.IntegerField(default=0, verbose_name='Download Count'),
        ),
    ]
