# Generated by Django 3.2.9 on 2021-11-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_slug'),
        ('gallery', '0025_galleryitem_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Item Owner'),
            preserve_default=False,
        ),
    ]
