# Generated by Django 3.2.9 on 2021-11-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0027_gallerytempfile_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerytempfile',
            name='file_size',
            field=models.FloatField(default=0, verbose_name='File Size'),
        ),
    ]
