# Generated by Django 3.2.9 on 2021-11-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0028_gallerytempfile_file_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerytempfile',
            old_name='profile',
            new_name='profile_old',
        ),
    ]
