# Generated by Django 3.2.9 on 2021-11-18 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_slug'),
        ('gallery', '0029_rename_profile_gallerytempfile_profile_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerytempfile',
            name='profile_old',
        ),
        migrations.AddField(
            model_name='gallerytempfile',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile'),
        ),
    ]
