# Generated by Django 3.2.9 on 2021-11-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0030_auto_20211118_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerytempfile',
            name='thumbnail',
            field=models.TextField(default='', verbose_name='File Thumbnail'),
            preserve_default=False,
        ),
    ]
