# Generated by Django 3.2.9 on 2021-11-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0031_gallerytempfile_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='temp_file',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='temp_file_name',
        ),
    ]
