# Generated by Django 3.2.9 on 2021-11-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0032_auto_20211124_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycatgroups',
            name='categories',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Category Count'),
        ),
        migrations.CreateModel(
            name='GalleryItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order Column')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gallery.galleryartworkcat', verbose_name='category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gallery.galleryitem', verbose_name='Item')),
            ],
        ),
    ]
