# Generated by Django 3.2.9 on 2021-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0033_auto_20211124_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycatgroupobject',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Item Active Flag'),
        ),
        migrations.AddField(
            model_name='gallerycatgroupobject',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Item Archived Flag'),
        ),
        migrations.AddField(
            model_name='gallerycatgroupobject',
            name='frozen',
            field=models.BooleanField(default=False, verbose_name='Item Frozen Flag'),
        ),
        migrations.AddField(
            model_name='gallerycatgroupobject',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Item Hidden Flag'),
        ),
    ]
