# Generated by Django 3.2.9 on 2021-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0034_auto_20211124_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycatgroupobject',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Item Active Flag'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Item Active Flag'),
        ),
    ]
