# Generated by Django 3.2.9 on 2021-11-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20211118_2107'),
        ('gallery', '0035_auto_20211124_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycollectionpermission',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community'),
        ),
    ]
