# Generated by Django 3.2.9 on 2021-11-24 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20211118_2107'),
        ('group', '0003_auto_20211118_2043'),
        ('gallery', '0036_gallerycollectionpermission_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycollectionpermission',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='gallerycollectionpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group'),
        ),
    ]
