# Generated by Django 3.2.9 on 2021-11-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0037_auto_20211124_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerycollectionpermission',
            old_name='collection',
            new_name='collection_old',
        ),
    ]
