# Generated by Django 3.2.9 on 2021-11-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0038_rename_collection_gallerycollectionpermission_collection_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerycollectionpermission',
            name='collection_old',
        ),
        migrations.AddField(
            model_name='gallerycollectionpermission',
            name='collection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycollection', verbose_name='Gallery Collection'),
            preserve_default=False,
        ),
    ]
