# Generated by Django 3.2.9 on 2021-11-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0039_auto_20211124_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerycollectionpermission',
            old_name='group',
            new_name='group_old',
        ),
        migrations.RenameField(
            model_name='gallerycollectionpermission',
            old_name='profile',
            new_name='profile_old',
        ),
    ]
