# Generated by Django 3.2.9 on 2021-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0041_auto_20211124_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerytempfile',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived FLAG'),
        ),
        migrations.AddField(
            model_name='gallerytempfile',
            name='publish_job',
            field=models.UUIDField(default=None, null=True, verbose_name='Publish Job UUID'),
        ),
        migrations.AddField(
            model_name='gallerytempfile',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published FLAG'),
        ),
    ]
