# Generated by Django 3.2.9 on 2021-11-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0043_remove_galleryitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitemfile',
            name='original',
            field=models.BooleanField(default=False, verbose_name='File is an Original'),
        ),
    ]
