# Generated by Django 3.2.9 on 2021-11-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0044_galleryitemfile_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitemfile',
            old_name='item',
            new_name='itemold',
        ),
    ]
