# Generated by Django 3.2.9 on 2021-11-28 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0045_rename_item_galleryitemfile_itemold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitemfile',
            name='itemold',
        ),
        migrations.AddField(
            model_name='galleryitemfile',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem', verbose_name='Item'),
            preserve_default=False,
        ),
    ]
