# Generated by Django 3.2.9 on 2021-11-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0046_auto_20211128_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='details',
            field=models.CharField(default=False, max_length=10, verbose_name='Item Details Flags'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='sizing',
            field=models.IntegerField(default=0, verbose_name='Sizing Hint'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='style',
            field=models.CharField(default=False, max_length=10, verbose_name='Item Style Flag'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='explicit',
            field=models.CharField(default=False, max_length=10, verbose_name='Item Explicit'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='nsfw',
            field=models.CharField(default=False, max_length=10, verbose_name='Item NSFW Flag'),
        ),
    ]
