# Generated by Django 3.2.9 on 2021-11-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0047_auto_20211129_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='explicit',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='raiting',
            field=models.CharField(default=False, max_length=10, verbose_name='Item Rating'),
        ),
    ]
