# Generated by Django 3.2.9 on 2021-11-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0048_auto_20211129_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitem',
            old_name='raiting',
            new_name='rating',
        ),
    ]
