# Generated by Django 3.2.9 on 2021-11-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0049_rename_raiting_galleryitem_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitemkeyword',
            old_name='keyword',
            new_name='keyword_old',
        ),
    ]
