# Generated by Django 3.2.9 on 2021-11-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_auto_20211125_1836'),
        ('gallery', '0050_rename_keyword_galleryitemkeyword_keyword_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitemkeyword',
            name='keyword_old',
        ),
        migrations.AddField(
            model_name='galleryitemkeyword',
            name='keyword',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='keywords.keyword', verbose_name='keyword'),
            preserve_default=False,
        ),
    ]
