# Generated by Django 3.2.9 on 2021-11-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0051_auto_20211129_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitemkeyword',
            old_name='item',
            new_name='item_old',
        ),
    ]
