# Generated by Django 3.2.9 on 2021-11-29 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0052_rename_item_galleryitemkeyword_item_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitemkeyword',
            name='item_old',
        ),
        migrations.AddField(
            model_name='galleryitemkeyword',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='gallery.galleryitem', verbose_name='Item'),
            preserve_default=False,
        ),
    ]
