# Generated by Django 3.2.9 on 2021-11-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0053_auto_20211129_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerycollectionitems',
            old_name='collection',
            new_name='collection_old',
        ),
        migrations.RenameField(
            model_name='gallerycollectionitems',
            old_name='item',
            new_name='item_old',
        ),
    ]
