# Generated by Django 3.2.9 on 2021-11-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0054_auto_20211129_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerycollectionitems',
            name='collection_old',
        ),
        migrations.RemoveField(
            model_name='gallerycollectionitems',
            name='item_old',
        ),
        migrations.AddField(
            model_name='gallerycollectionitems',
            name='collection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycollection', verbose_name='Collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerycollectionitems',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem', verbose_name='Item'),
            preserve_default=False,
        ),
    ]
