# Generated by Django 4.0.2 on 2022-02-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0056_galleryitemsbycollectionpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitemcomments',
            name='profile',
        ),
    ]
