# Generated by Django 4.0.2 on 2022-02-18 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_profilepermission_profile_profilepermission_visitor'),
        ('gallery', '0057_remove_galleryitemcomments_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitemcomments',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Item'),
            preserve_default=False,
        ),
    ]
