# Generated by Django 4.0.2 on 2022-04-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0058_galleryitemcomments_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitemcomments',
            name='item',
        ),
    ]
