# Generated by Django 4.0.2 on 2022-04-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0059_remove_galleryitemcomments_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitemcomments',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='gallery.galleryitem', verbose_name='Item'),
            preserve_default=False,
        ),
    ]
