# Generated by Django 4.2.4 on 2023-08-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='content_manager_categories_category',
        ),
    ]
