# Generated by Django 4.0.2 on 2022-05-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_streamthread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streammessagekeywords',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.stream', verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='streamthread',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.stream', verbose_name='Stream'),
        ),
    ]
