# Generated by Django 4.0.2 on 2022-05-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_alter_streammessagekeywords_stream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='processed',
        ),
    ]
