# Generated by Django 4.0.2 on 2022-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_stream_bkg1_stream_bkg2_stream_bkgt_stream_midpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='opened',
            field=models.BooleanField(default=False, verbose_name='Stream FLAG: has been Opened'),
        ),
    ]
