# Generated by Django 4.0.4 on 2022-05-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0012_streammessage_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streammessage',
            name='community',
        ),
    ]
