# Generated by Django 4.0.4 on 2022-05-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0013_remove_streammessage_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammessage',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Like Count'),
        ),
        migrations.AddField(
            model_name='streammessage',
            name='reposts',
            field=models.IntegerField(default=0, verbose_name='Reposts Count'),
        ),
        migrations.AddField(
            model_name='streammessage',
            name='threads',
            field=models.IntegerField(default=0, verbose_name='Thread Count'),
        ),
    ]
