# Generated by Django 4.0.4 on 2022-05-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0015_streammessage_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammessage',
            name='replies',
            field=models.IntegerField(default=0, verbose_name='Replies Count'),
        ),
    ]
