# Generated by Django 4.0.4 on 2022-08-31 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0020_stream_name_stream_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Type Created')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Type Name')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Type Descr')),
            ],
        ),
        migrations.AddConstraint(
            model_name='streamtype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_stream_type'),
        ),
    ]
