# Generated by Django 4.0.4 on 2022-08-31 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0022_stream_streamtype_alter_stream_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='streamtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='stream.streamtype', verbose_name='Stream Type (public)'),
        ),
    ]
