# Generated by Django 4.0.4 on 2022-08-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0024_remove_streamtype_unique_stream_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('tag', 'profile', 'community'), name='unique_stream_tag'),
        ),
    ]
