# Generated by Django 4.0.4 on 2022-08-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0026_alter_stream_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='Stream Description'),
        ),
    ]
