# Generated by Django 4.2.4 on 2023-11-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banList',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timeLastSync',
        ),
        migrations.RemoveField(
            model_name='event',
            name='uniqueBadgeNumbers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='uniqueBadgeNumbersCard',
        ),
        migrations.AlterField(
            model_name='event',
            name='aaClose',
            field=models.DateTimeField(help_text='End of Applications Period', verbose_name='Applications Close'),
        ),
        migrations.AlterField(
            model_name='event',
            name='aaOpen',
            field=models.DateTimeField(help_text='Start of Applications Period', verbose_name='Applications Open'),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, help_text='Enable/open Event', verbose_name='Event Active'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealersClose',
            field=models.DateTimeField(help_text="End of Dealers' den being open", verbose_name='Dealers Den Close'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealersOpen',
            field=models.DateTimeField(help_text="Start of Dealers' den being open", verbose_name='Dealers Den Open'),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateField(blank=True, help_text='Event End Date', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventsClose',
            field=models.DateTimeField(help_text='End of Events Period', verbose_name='Events Close'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventsOpen',
            field=models.DateTimeField(help_text='Start of Events Period', verbose_name='Events Open'),
        ),
        migrations.AlterField(
            model_name='event',
            name='isSecAccessEnabled',
            field=models.BooleanField(default=False, help_text='Enables the PocketSec application to be used by PSafe', verbose_name='Enable PSafe'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Will be displayed EVERYWHERE.', max_length=100, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='regClose',
            field=models.DateTimeField(help_text='Date registration closes', verbose_name='Registration Close'),
        ),
        migrations.AlterField(
            model_name='event',
            name='regEditClose',
            field=models.DateTimeField(help_text='End of period during which registration edits are allowed', verbose_name='Registration Editing Period Close'),
        ),
        migrations.AlterField(
            model_name='event',
            name='regEditOpen',
            field=models.DateTimeField(help_text='Start of period during which registration edits are allowed', verbose_name='Registration Editing Period Open'),
        ),
        migrations.AlterField(
            model_name='event',
            name='regOpen',
            field=models.DateTimeField(help_text='Date registration opens', verbose_name='Registration Open'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(blank=True, help_text='Event Start Date', null=True, verbose_name='Start Date'),
        ),
    ]
