# Generated by Django 3.1.3 on 2022-05-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('marketplace', '0001_initial'),
        ('registration', '0009_auto_20220405_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottable',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.dealer'),
        ),
        migrations.AddField(
            model_name='hottable',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
        ),
    ]
