# Generated by Django 4.2.4 on 2023-11-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_banlist_remove_event_timelastsync_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='regEditClose',
        ),
        migrations.RemoveField(
            model_name='event',
            name='regEditOpen',
        ),
    ]
