# Generated by Django 4.2.4 on 2023-11-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_regeditclose_remove_event_regeditopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='aaClose',
            field=models.DateTimeField(help_text='End of Applications Period', verbose_name='Applications Accepted Close'),
        ),
        migrations.AlterField(
            model_name='event',
            name='aaOpen',
            field=models.DateTimeField(help_text='Start of Applications Period', verbose_name='Applications Accepted Open'),
        ),
        migrations.AlterField(
            model_name='eventcommunitymapping',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Event'),
        ),
    ]
