# Generated by Django 4.2.4 on 2023-08-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('dynapages', '0001_initial'),
        ('community', '0001_initial'),
        ('group', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Friend 1 Profile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='friend2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Friend 2 Profile'),
        ),
        migrations.AddField(
            model_name='follower',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='follower',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Dest Profile'),
        ),
        migrations.AddField(
            model_name='follower',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile'),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='communityadmins',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='communityadmins',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='community',
            name='backgroundItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.galleryitem'),
        ),
        migrations.AddField(
            model_name='community',
            name='dynapage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dynapages.page'),
        ),
    ]
