# Generated by Django 4.0.2 on 2022-05-07 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePerCoummunityView',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined', models.DateTimeField(auto_now_add=True, verbose_name='Profile Joined')),
                ('name', models.TextField(verbose_name='Community Name')),
                ('placeholder', models.BooleanField(default=False, verbose_name='Placeholder FLAG')),
                ('profile_created', models.DateTimeField(auto_now_add=True, verbose_name='Profile Created')),
                ('profile_updated', models.DateTimeField(auto_now_add=True, verbose_name='Profile Updated')),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='Profile Last Seen Online')),
                ('age', models.TextField(blank=True, default=1, verbose_name='Current Age')),
                ('profile_name', models.TextField(verbose_name='Profile Name')),
                ('status', models.TextField(blank=True, default='CITIZEN', verbose_name='status')),
                ('species', models.TextField(default='Sentient', verbose_name='Species')),
                ('introduction', models.TextField(verbose_name='Profile Intro')),
                ('level', models.TextField(default=1, verbose_name='Current Level')),
                ('max_HP', models.TextField(default=10, verbose_name='Max HP')),
                ('HP', models.TextField(default=10, verbose_name='Current HP')),
                ('max_MP', models.TextField(default=6, verbose_name='Max MP')),
                ('STUN', models.TextField(default=10, verbose_name='Current STUN')),
                ('max_STUN', models.TextField(default=6, verbose_name='Max STUN')),
                ('SHIELD', models.TextField(default=10, verbose_name='Current SHIELD')),
                ('max_SHIELD', models.TextField(default=6, verbose_name='Max SHIELD')),
                ('MP', models.TextField(default=6, verbose_name='Current MP')),
                ('max_STA', models.TextField(default=10, verbose_name='Max STA')),
                ('STA', models.TextField(default=10, verbose_name='Current STA')),
                ('slug', models.TextField(verbose_name='Slugified Name')),
                ('pronouns', models.TextField(max_length=200, verbose_name='Pronouns')),
                ('gender', models.TextField(max_length=200, verbose_name='Gender')),
                ('avatar', models.TextField(blank=True, null=True, verbose_name='Avatar URL')),
                ('posts', models.IntegerField(default=0, verbose_name='Post Count')),
                ('views', models.IntegerField(default=0, verbose_name='Post Count')),
                ('nodes', models.IntegerField(default=0, verbose_name='Node Count')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'community_profilepercommunityview',
                'managed': False,
            },
        ),
    ]
