# Generated by Django 4.2.4 on 2023-10-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Community Icon'),
        ),
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Community Logo'),
        ),
        migrations.AlterField(
            model_name='communityadmins',
            name='joined',
            field=models.DateTimeField(auto_now=True, verbose_name='Joined'),
        ),
        migrations.AlterModelTable(
            name='profilepercoummunityview',
            table='community_profile_per_community_view',
        ),
    ]
