# Generated by Django 4.2.4 on 2023-10-09 01:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_alter_community_tagline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Community Icon"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Community Logo"
            ),
        ),
        migrations.CreateModel(
            name="CommunityRegistry",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.TextField(max_length=200, verbose_name="Setting key")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Setting Created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Setting Updated"
                    ),
                ),
                ("name", models.TextField(verbose_name="Setting Name")),
                (
                    "action_call_cover",
                    models.TextField(verbose_name="Action Call for Cover page"),
                ),
                (
                    "text_value",
                    models.TextField(blank=True, null=True, verbose_name="Text Value"),
                ),
                (
                    "int_value",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Int Value"
                    ),
                ),
                (
                    "json_value",
                    models.JSONField(blank=True, null=True, verbose_name="Json Value"),
                ),
                (
                    "bin_value",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Binary Value"
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.community",
                        verbose_name="Community",
                    ),
                ),
            ],
            options={
                "db_table": "communities_community_community_registry",
                "unique_together": {("community", "key")},
            },
        ),
    ]
