# Generated by Django 4.0.4 on 2022-09-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_communityprofile_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_ExpLvl_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend1_id', models.UUIDField(verbose_name='Friend 1 UUID')),
                ('approved', models.DateTimeField(null=True, verbose_name='Approved?')),
                ('approved_flag', models.BooleanField(default=False, verbose_name='Approved FLAG')),
                ('friend2_id', models.UUIDField(verbose_name='Friend 2 UUID')),
                ('profile_id', models.CharField(max_length=200, verbose_name='Profile ID')),
                ('updated', models.DateTimeField(verbose_name='Friendship Updated')),
                ('age', models.IntegerField(verbose_name='Profile Age')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('class_name', models.CharField(max_length=200, verbose_name='Class Name')),
                ('status', models.CharField(max_length=200, verbose_name='Status')),
                ('species', models.CharField(max_length=200, verbose_name='Species')),
                ('introduction', models.TextField(verbose_name='Profile Intro')),
                ('slug', models.TextField(verbose_name='Slugified Name')),
                ('pronouns', models.TextField(max_length=200, verbose_name='Pronouns')),
                ('gender', models.TextField(max_length=200, verbose_name='Gender')),
                ('avatar', models.TextField(blank=True, null=True, verbose_name='Avatar URL')),
                ('level_id', models.UUIDField(verbose_name='Level UUID')),
                ('classtype_id', models.UUIDField(verbose_name='Classtype UUID')),
                ('community_id', models.UUIDField(verbose_name='Community UUID')),
                ('expr', models.IntegerField(verbose_name='Experience Points')),
                ('current_level', models.IntegerField(verbose_name='Current Level')),
            ],
            options={
                'db_table': 'community_friend_explvl_view',
                'managed': False,
            },
        ),
    ]
