# Generated by Django 4.2.4 on 2023-10-09 01:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0006_alter_communityregistry_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunitySidebarMenu",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_mode",
                    models.TextField(max_length=200, verbose_name="Application Mode"),
                ),
                ("module", models.TextField(max_length=200, verbose_name="Module")),
                (
                    "sidebar_class",
                    models.TextField(max_length=200, verbose_name="Sidebar Class"),
                ),
                (
                    "ordering",
                    models.IntegerField(default=1, verbose_name="Ordering Key"),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Entry Active"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.community",
                        verbose_name="Community",
                    ),
                ),
            ],
            options={
                "db_table": "communities_community_sidebar",
                "ordering": ["community", "application_mode", "ordering"],
                "unique_together": {("community", "module", "sidebar_class")},
            },
        ),
    ]
