# Generated by Django 4.2.4 on 2023-12-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_communitydashboardtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitydashboardtype',
            name='community',
        ),
    ]
