# Generated by Django 4.2.4 on 2023-12-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_remove_communitydashboardtype_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitydashboardtype',
            old_name='dashboard_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='communitydashboardtype',
            name='name',
            field=models.TextField(default='', max_length=200, verbose_name='Dashboard Type Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitydashboardtype',
            name='privileged',
            field=models.BooleanField(default=False, verbose_name='Dashboard type is privileged'),
        ),
    ]
