# Generated by Django 4.2.4 on 2023-12-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('community', '0016_communitydashboardtype_descr'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now=True, verbose_name='Joined')),
                ('active', models.BooleanField(default=True, verbose_name='Active FLAG')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='User')),
            ],
            options={
                'db_table': 'communities_community_community_staff',
            },
        ),
    ]
