# Generated by Django 4.2.4 on 2023-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_communitystaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitystaff',
            name='joined',
        ),
        migrations.AddField(
            model_name='communitystaff',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
    ]
