# Generated by Django 4.2.4 on 2023-12-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('community', '0018_remove_communitystaff_joined_communitystaff_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityadmins',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Staff Created'),
        ),
        migrations.AlterField(
            model_name='communityadmins',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='communitystaff',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='communityadmins',
            unique_together={('community', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='communitystaff',
            unique_together={('community', 'profile')},
        ),
        migrations.RemoveField(
            model_name='communityadmins',
            name='joined',
        ),
    ]
