# Generated by Django 4.2.4 on 2023-12-07 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_communityadmins_created_alter_communityadmins_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitystaff',
            name='id',
        ),
        migrations.AddField(
            model_name='communitystaff',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
