# Generated by Django 5.0.1 on 2024-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_alter_communitysidebarmenu_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vhost',
            name='ipaddr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='VHost IP address'),
        ),
    ]
