# Generated by Django 5.0.1 on 2024-05-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0026_alter_communitysidebarmenu_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitysidebarmenu",
            name="not_edited",
            field=models.BooleanField(
                default=False,
                help_text="IGNORE: Internal control flag",
                verbose_name="Not Edited",
            ),
        ),
        migrations.AlterField(
            model_name="communitysidebarmenu",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="communitysidebarmenu",
            name="application_mode",
            field=models.TextField(
                choices=[
                    ("world_forge", "world_forge"),
                    ("user", "user"),
                    ("staff", "staff"),
                ],
                help_text="Dashboard Application Mode to create menu for",
                max_length=200,
                verbose_name="Application Mode:",
            ),
        ),
        migrations.AlterField(
            model_name="communitysidebarmenu",
            name="module",
            field=models.TextField(
                choices=[
                    ("communities.community", "communities.community"),
                    ("communities.dashboards", "communities.dashboards"),
                    ("media.gallery.core", "media.gallery.core"),
                    ("ufls.event", "ufls.event"),
                    ("ufls.registrar", "ufls.registrar"),
                ],
                help_text="Application to Include in the Menus",
                max_length=200,
                verbose_name="Module/AppName:",
            ),
        ),
        migrations.AlterField(
            model_name="communitysidebarmenu",
            name="ordering",
            field=models.IntegerField(
                default=1,
                help_text="Ordering Key to assemble menus",
                verbose_name="Ordering Key:",
            ),
        ),
        migrations.AlterField(
            model_name="communitysidebarmenu",
            name="sidebar_class",
            field=models.TextField(
                default="sidebar_menu",
                help_text="Sidebar class to load for menu",
                max_length=200,
                verbose_name="Sidebar Class:",
            ),
        ),
    ]
