# Generated by Django 5.0.1 on 2024-05-11 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0027_communitysidebarmenu_not_edited_and_more"),
        ("dynapages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitysidebarmenu",
            name="module",
            field=models.TextField(
                choices=[
                    ("communities.community", "communities.community"),
                    ("communities.dashboards", "communities.dashboards"),
                    ("media.gallery.core", "media.gallery.core"),
                    ("ufls.event", "ufls.event"),
                    ("ufls.registrar", "ufls.registrar"),
                    ("ufls.staff", "ufls.staff"),
                ],
                help_text="Application to Include in the Menus",
                max_length=200,
                verbose_name="Module/AppName:",
            ),
        ),
        migrations.AlterField(
            model_name="communitysidebarmenu",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="CommunityDashboardTypeWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Widget Created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Widget Updated"),
                ),
                (
                    "banner",
                    models.BooleanField(default=False, verbose_name="Banner Mode"),
                ),
                (
                    "mainbody",
                    models.BooleanField(default=False, verbose_name="MainBody Mode"),
                ),
                (
                    "sidecol",
                    models.BooleanField(default=False, verbose_name="SideColumn Mode"),
                ),
                (
                    "footer",
                    models.BooleanField(default=False, verbose_name="Footer Mode"),
                ),
                (
                    "pos",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Widget Position (Column)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Widget Order")),
                (
                    "thumbnail",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Widget Thumbnail",
                    ),
                ),
                (
                    "plugin_data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Widget plugin-specific data",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Active FLAG"),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.communitydashboardtype",
                        verbose_name="Dashboard",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dynapages.widget",
                        verbose_name="Widget",
                    ),
                ),
            ],
            options={
                "db_table": "community_dashboard_type_widget",
            },
        ),
    ]
