# Generated by Django 5.0.1 on 2024-05-11 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0028_alter_communitysidebarmenu_module_and_more"),
        ("dynapages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityProfileDashboardRolesWidgets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Widget Created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Widget Updated"),
                ),
                (
                    "banner",
                    models.BooleanField(default=False, verbose_name="Banner Mode"),
                ),
                (
                    "mainbody",
                    models.BooleanField(default=False, verbose_name="MainBody Mode"),
                ),
                (
                    "sidecol",
                    models.BooleanField(default=False, verbose_name="SideColumn Mode"),
                ),
                (
                    "footer",
                    models.BooleanField(default=False, verbose_name="Footer Mode"),
                ),
                (
                    "pos",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Widget Position (Column)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Widget Order")),
                (
                    "thumbnail",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Widget Thumbnail",
                    ),
                ),
                (
                    "plugin_data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Widget plugin-specific data",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Active FLAG"),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.communityprofiledashboardroles",
                        verbose_name="Dashboard",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dynapages.widget",
                        verbose_name="Widget",
                    ),
                ),
            ],
            options={
                "db_table": "communities_community_community_profile_dashboard_roles_widgets",
            },
        ),
        migrations.DeleteModel(
            name="CommunityDashboardTypeWidget",
        ),
    ]
