# Generated by Django 5.0.1 on 2024-05-11 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0029_communityprofiledashboardroleswidgets_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommunityProfileDashboardRolesWidgets",
        ),
    ]
