# Generated by Django 5.0.1 on 2024-05-11 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0031_communityprofiledashboardroles_landing_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communityprofiledashboardroles",
            old_name="landing_page",
            new_name="dynapage_landing",
        ),
    ]
