# Generated by Django 5.0.1 on 2024-05-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "community",
            "0032_rename_landing_page_communityprofiledashboardroles_dynapage_landing",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="communityregistry",
            name="uuid_value",
            field=models.UUIDField(blank=True, null=True, verbose_name="UUID Value"),
        ),
    ]
