# Generated by Django 5.0.1 on 2024-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0034_communityregistry_grouping_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityregistry",
            name="foreign_key_ref",
            field=models.TextField(
                blank=True, null=True, verbose_name="Foreign Key Reference (if used)"
            ),
        ),
    ]
