# Generated by Django 5.0.1 on 2024-05-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0036_remove_communityregistry_action_call_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityRegistryPageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.TextField(
                        max_length=300, unique=True, verbose_name="Setting Key"
                    ),
                ),
                (
                    "grouping_key",
                    models.TextField(
                        max_length=300,
                        unique=True,
                        verbose_name="Setting Community Grouping",
                    ),
                ),
                (
                    "slug",
                    models.TextField(
                        max_length=300, unique=True, verbose_name="Page slug"
                    ),
                ),
                ("label", models.TextField(max_length=200, verbose_name="Page Label")),
                (
                    "system",
                    models.BooleanField(default=False, verbose_name="System Page"),
                ),
            ],
            options={
                "db_table": "communities_community_registry_page_view",
                "managed": False,
            },
        ),
    ]
