# Generated by Django 5.0.1 on 2024-05-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_alter_communitysidebarmenu_module_and_more'),
        ('community', '0037_communityregistrypageview'),
    ]

    operations = [
    ]
