# Generated by Django 5.0.1 on 2024-05-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0038_merge_20240518_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitysidebarmenu',
            name='module',
            field=models.TextField(choices=[('communities.community', 'communities.community'), ('communities.dashboards', 'communities.dashboards'), ('media.gallery.core', 'media.gallery.core')], help_text='Application to Include in the Menus', max_length=200, verbose_name='Module/AppName:'),
        ),
    ]
