# Generated by Django 5.0.1 on 2024-07-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0038_alter_communitysidebarmenu_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityregistry",
            name="bool_value",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Boolean Value"
            ),
        ),
    ]
