# Generated by Django 5.0.1 on 2024-07-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0038_alter_communitysidebarmenu_module'),
        ('community', '0039_alter_communitysidebarmenu_module'),
    ]

    operations = [
    ]
