# Generated by Django 5.0.1 on 2024-07-24 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0024_alter_communitysidebarmenu_module"),
        ("community", "0039_communityregistry_bool_value"),
        ("community", "0040_merge_20240717_2027"),
    ]

    operations = []
