# Generated by Django 5.0.1 on 2024-07-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0041_alter_communitysidebarmenu_module'),
        ('community', '0041_merge_20240723_2158'),
    ]

    operations = [
    ]
