# Generated by Django 5.0.1 on 2024-08-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0043_alter_communitysidebarmenu_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitysidebarmenu",
            name="module",
            field=models.TextField(
                choices=[
                    ("communities.preferences", "communities.preferences"),
                    ("communities.community", "communities.community"),
                    ("communities.dashboards", "communities.dashboards"),
                    ("media.gallery.core", "media.gallery.core"),
                    ("leagues.sports", "leagues.sports"),
                ],
                help_text="Application to Include in the Menus",
                max_length=200,
                verbose_name="Module/AppName:",
            ),
        ),
    ]
