# Generated by Django 4.0.2 on 2022-04-26 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('profiles', '0001_initial'),
        ('keywords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynapages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='group.grouptitle', verbose_name='Group Title'),
        ),
        migrations.AddField(
            model_name='groupkeywords',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Groups'),
        ),
        migrations.AddField(
            model_name='groupkeywords',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='keywords.keyword', verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User (Creator)'),
        ),
        migrations.AddField(
            model_name='group',
            name='creator_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profile (Creator)'),
        ),
        migrations.AddField(
            model_name='group',
            name='dynapage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dynapages.page'),
        ),
    ]
