# Generated by Django 3.2.9 on 2021-11-18 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupkeywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AddField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
