# Generated by Django 3.2.9 on 2022-02-03 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0001_initial'),
        ('group', '0003_auto_20211118_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='dynapage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dynapages.page'),
        ),
    ]
