# Generated by Django 4.0.2 on 2022-02-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_dynapage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupkeywords',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Groups'),
        ),
        migrations.CreateModel(
            name='GroupTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Title')),
                ('order', models.IntegerField(default=0, verbose_name='Order Column')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group')),
            ],
        ),
    ]
