# Generated by Django 4.0.2 on 2022-02-11 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_profile_age_profile_last_seen'),
        ('group', '0005_alter_groupkeywords_group_grouptitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='group.grouptitle', verbose_name='Group Title')),
            ],
        ),
    ]
