# Generated by Django 4.0.2 on 2022-02-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_group_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creator_profile',
        ),
    ]
