# Generated by Django 4.0.2 on 2022-02-11 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_profile_species'),
        ('group', '0009_remove_group_creator_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profile (Creator)'),
            preserve_default=False,
        ),
    ]
