# Generated by Django 4.0.2 on 2022-02-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_group_creator_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Primary FLAG'),
        ),
    ]
