# Generated by Django 4.0.4 on 2022-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='starting',
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('community', 'level'), name='unique_level'),
        ),
    ]
