# Generated by Django 4.0.4 on 2022-08-23 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_profilepagenodes_profilepagenode'),
        ('community', '0006_alter_communityprofile_profile'),
        ('stats', '0003_classtype_classtypestat'),
        ('plyscript', '0006_alter_script_function_name_alter_script_name'),
        ('exp', '0002_remove_level_starting_level_unique_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='expr',
            field=models.IntegerField(default=0, verbose_name='Experience Required'),
        ),
        migrations.AlterField(
            model_name='level',
            name='statpoints',
            field=models.IntegerField(default=5, verbose_name='Stat Points Awarded'),
        ),
        migrations.CreateModel(
            name='ProfileExperience',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expr', models.IntegerField(default=0, verbose_name='Current Experience')),
                ('statpoints', models.IntegerField(default=0, verbose_name='Stat Points Available')),
                ('classtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.classtype', verbose_name='Class Type')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plyscript.script', verbose_name='Current Level')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profile')),
            ],
        ),
        migrations.CreateModel(
            name='LevelScript',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.classtype', verbose_name='Class Type')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.level', verbose_name='Level Reached')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plyscript.script', verbose_name='Script Callable')),
            ],
        ),
        migrations.AddConstraint(
            model_name='profileexperience',
            constraint=models.UniqueConstraint(fields=('community', 'profile'), name='unique_profile_exp'),
        ),
        migrations.AddConstraint(
            model_name='levelscript',
            constraint=models.UniqueConstraint(fields=('community', 'classtype', 'script', 'level'), name='unique_class_level_script'),
        ),
    ]
