# Generated by Django 4.0.4 on 2022-08-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_alter_level_expr_alter_level_statpoints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileexperience',
            name='level',
        ),
    ]
