# Generated by Django 4.0.4 on 2022-08-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0004_remove_profileexperience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileexperience',
            name='level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exp.level', verbose_name='Current Level'),
        ),
    ]
