# Generated by Django 4.0.4 on 2022-08-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plyscript', '0006_alter_script_function_name_alter_script_name'),
        ('exp', '0005_profileexperience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plyscript.script', verbose_name='Run Script on Awarding Level'),
        ),
        migrations.AlterField(
            model_name='profileexperience',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.level', verbose_name='Current Level'),
        ),
    ]
