# Generated by Django 4.0.4 on 2022-08-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0006_alter_level_script_alter_profileexperience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='skillpoints',
            field=models.IntegerField(default=2, verbose_name='Skill Points Awarded'),
        ),
        migrations.AddField(
            model_name='profileexperience',
            name='skillpoints',
            field=models.IntegerField(default=0, verbose_name='Skill Points Available'),
        ),
    ]
