# Generated by Django 4.0.4 on 2022-08-24 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_communityprofile_profile'),
        ('stats', '0006_basestat_descr'),
        ('profiles', '0009_rename_profilepagenodes_profilepagenode'),
        ('plyscript', '0006_alter_script_function_name_alter_script_name'),
        ('exp', '0007_level_skillpoints_profileexperience_skillpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelscript',
            name='classtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stats.classtype', verbose_name='Class Type'),
        ),
        migrations.AlterField(
            model_name='levelscript',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exp.level', verbose_name='Level Reached'),
        ),
        migrations.AlterField(
            model_name='levelscript',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plyscript.script', verbose_name='Script Callable'),
        ),
        migrations.AlterField(
            model_name='profileexperience',
            name='classtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stats.classtype', verbose_name='Class Type'),
        ),
        migrations.AlterField(
            model_name='profileexperience',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exp.level', verbose_name='Current Level'),
        ),
        migrations.AlterField(
            model_name='profileexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.CreateModel(
            name='ProfileExperienceHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expr', models.IntegerField(default=0, verbose_name='Current Experience')),
                ('statpoints', models.IntegerField(default=0, verbose_name='Stat Points Assigned')),
                ('skillpoints', models.IntegerField(default=0, verbose_name='Skill Points Assigned')),
                ('reason', models.TextField(verbose_name='Logged Reason')),
                ('classtype', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stats.classtype', verbose_name='Class Type')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exp.level', verbose_name='Current Level')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile')),
            ],
        ),
    ]
