# Generated by Django 4.0.4 on 2022-08-24 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0009_alter_levelscript_classtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileexperiencehistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
