# Generated by Django 4.0.2 on 2022-02-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestat',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='Icon'),
        ),
    ]
