# Generated by Django 4.0.2 on 2022-05-10 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0005_friend_community'),
        ('profiles', '0003_profile_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Stream Created')),
                ('type', models.TextField(verbose_name='Stream Type')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Stream Icon')),
                ('shares', models.IntegerField(default=0, verbose_name='Share Count')),
                ('views', models.IntegerField(default=0, verbose_name='Views Count')),
                ('nodes', models.IntegerField(default=0, verbose_name='Node Count')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('delivered', models.BooleanField(default=False, verbose_name='DELIVERED FLAG')),
                ('processed', models.BooleanField(default=False, verbose_name='PROCESSED FLAG')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
            ],
        ),
        migrations.CreateModel(
            name='StreamSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Notification Inbox Created')),
                ('last_view', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last Viewed')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.stream', verbose_name='Notification')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Subscriber Profile')),
            ],
        ),
        migrations.CreateModel(
            name='StreamMessage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Stream Created')),
                ('type', models.TextField(verbose_name='Message Type')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Message Icon')),
                ('shares', models.IntegerField(default=0, verbose_name='Share Count')),
                ('views', models.IntegerField(default=0, verbose_name='Views Count')),
                ('contents_text', models.TextField(blank=True, null=True, verbose_name='Stream Content: Text Type')),
                ('contents_json', models.JSONField(blank=True, null=True, verbose_name='Stream Content: JSON Type')),
                ('contents_bin', models.BinaryField(blank=True, null=True, verbose_name='Stream Content: Binary Type')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Author')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
            ],
        ),
    ]
