# Generated by Django 4.2.4 on 2023-10-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messagesperstreamview',
            table='communities_stream_message_view',
        ),
    ]
