# Generated by Django 4.0.2 on 2022-05-10 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamMessageKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.keyword', verbose_name='Keyword')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.streammessage', verbose_name='Message')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.stream', verbose_name='Notification')),
            ],
        ),
    ]
