# Generated by Django 4.2.4 on 2023-12-14 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_remove_communityadmins_id_communityadmins_uuid'),
        ('stream', '0002_alter_messagesperstreamview_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamXMPPSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, help_text='Enable the XMPP Subsystem and integration with Ejabberd and the global XMPP network.', verbose_name='Enable XMPP Subsystem')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
            ],
            options={
                'db_table': 'communities_stream_stream_xmpp_settings',
            },
        ),
    ]
