# Generated by Django 4.2.4 on 2023-12-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_streamxmppsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamxmppsettings',
            name='endpoint',
            field=models.TextField(default='', help_text='Ejabberd mod_http management API endpoint URL', verbose_name='XMPP API REST Endpoint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamxmppsettings',
            name='server',
            field=models.TextField(default='', help_text='XMPP Server Hostname (where clients connect to)', verbose_name='XMPP Server Hostname'),
            preserve_default=False,
        ),
    ]
