# Generated by Django 4.2.4 on 2023-12-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_streamxmppsettings_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamxmppsettings',
            name='domain',
            field=models.TextField(default='', help_text='XMPP Server Domain (For JID creation: user@fqdn)', verbose_name='XMPP Server FQDN'),
            preserve_default=False,
        ),
    ]
