# Generated by Django 4.2.4 on 2023-12-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_streamxmppsettings_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamxmppsettings',
            name='self_reg',
            field=models.BooleanField(default=True, help_text='Allow users to register JIDs by themselves: profile@fqdn', verbose_name='Enable User self-registration'),
        ),
    ]
