# Generated by Django 4.0.2 on 2022-05-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
        ('profiles', '0003_profile_notifications'),
        ('community', '0005_friend_community'),
        ('stream', '0005_remove_stream_delivered_remove_stream_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='stream',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='stream',
            name='root_stream',
            field=models.BooleanField(default=False, verbose_name='Root Stream FLAG'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community'),
        ),
    ]
