# Generated by Django 4.2.4 on 2023-12-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_streamxmppsettings_self_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamxmppsettings',
            name='auto_group',
            field=models.BooleanField(default=True, help_text='Automatically create a MUC (Multi User Channel/Chat) for any created groups', verbose_name='Automatic MUC for Groups'),
        ),
        migrations.AlterField(
            model_name='streamxmppsettings',
            name='self_reg',
            field=models.BooleanField(default=True, help_text='Allow users to register JIDs by themselves: profile@fqdn from their User Dashboard', verbose_name='Enable User self-registration'),
        ),
    ]
