# Generated by Django 4.2.4 on 2023-12-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_streamxmppsettings_auto_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamxmppsettings',
            name='grant_admin',
            field=models.BooleanField(default=True, help_text='For Profiles with ADMIN Status, grant XMPP Admin status during creation.', verbose_name='Grant XMPP Admin for Admin Profiles'),
        ),
        migrations.AddField(
            model_name='streamxmppsettings',
            name='grant_admin2staff',
            field=models.BooleanField(default=False, help_text='For Profiles with Staff Status, grant XMPP Admin status during creation.', verbose_name='Grant XMPP Admin for Staff Profiles'),
        ),
        migrations.AddField(
            model_name='streamxmppsettings',
            name='grant_mod',
            field=models.BooleanField(default=False, help_text='For Profiles with ADMIN Status, grant XMPP Mod status during creation.', verbose_name='Grant XMPP Mod for Admin Profiles'),
        ),
        migrations.AddField(
            model_name='streamxmppsettings',
            name='grant_mod2staff',
            field=models.BooleanField(default=True, help_text='For Profiles with Staff Status, grant XMPP Mod status during creation.', verbose_name='Grant XMPP Mod for Staff Profiles'),
        ),
    ]
