# Generated by Django 4.2.4 on 2023-12-14 22:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_remove_communityadmins_id_communityadmins_uuid'),
        ('profiles', '0001_initial'),
        ('stream', '0008_streamxmppsettings_grant_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamProfileXMPPSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Settings Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Settings Updated')),
            ],
            options={
                'db_table': 'communities_stream_stream_xmpp_profile_settings',
            },
        ),
        migrations.AlterField(
            model_name='streamxmppsettings',
            name='grant_admin',
            field=models.BooleanField(default=True, help_text='For Profiles with ADMIN Status, grant XMPP Admin status during JID creation.', verbose_name='Grant XMPP Admin for Admin Profiles'),
        ),
        migrations.AlterField(
            model_name='streamxmppsettings',
            name='grant_admin2staff',
            field=models.BooleanField(default=False, help_text='For Profiles with Staff Status, grant XMPP Admin status during JID creation.', verbose_name='Grant XMPP Admin for Staff Profiles'),
        ),
        migrations.AlterField(
            model_name='streamxmppsettings',
            name='grant_mod',
            field=models.BooleanField(default=False, help_text='For Profiles with ADMIN Status, grant XMPP Mod status during JID creation.', verbose_name='Grant XMPP Mod for Admin Profiles'),
        ),
        migrations.AlterField(
            model_name='streamxmppsettings',
            name='grant_mod2staff',
            field=models.BooleanField(default=True, help_text='For Profiles with Staff Status, grant XMPP Mod status during JID creation.', verbose_name='Grant XMPP Mod for Staff Profiles'),
        ),
        migrations.AddConstraint(
            model_name='streamxmppsettings',
            constraint=models.UniqueConstraint(fields=('community',), name='unique_xmpp_settings'),
        ),
        migrations.AddField(
            model_name='streamprofilexmppsettings',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='streamprofilexmppsettings',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AddConstraint(
            model_name='streamprofilexmppsettings',
            constraint=models.UniqueConstraint(fields=('profile', 'community'), name='unique_stream_xmpp_profile'),
        ),
    ]
