# Generated by Django 4.0.2 on 2022-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_stream_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='default_perm',
            field=models.TextField(default='e', verbose_name='Stream Default Permission'),
        ),
    ]
