# Generated by Django 4.2.4 on 2023-12-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_streamprofilexmppsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprofilexmppsettings',
            name='jid',
            field=models.TextField(default='', verbose_name='JID'),
            preserve_default=False,
        ),
    ]
