# Generated by Django 4.2.4 on 2023-12-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0010_streamprofilexmppsettings_jid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='streamprofilexmppsettings',
            constraint=models.UniqueConstraint(fields=('jid',), name='unique_stream_xmpp_jid'),
        ),
    ]
