# Generated by Django 4.0.4 on 2022-05-20 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0011_alter_streammessage_contents_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammessage',
            name='stream',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stream.stream', verbose_name='Stream'),
            preserve_default=False,
        ),
    ]
