# Generated by Django 4.2.4 on 2024-01-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0012_remove_streamxmppsettings_grant_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprofilexmppmucs',
            name='descr',
            field=models.TextField(default='', verbose_name='Room Description'),
            preserve_default=False,
        ),
    ]
