# Generated by Django 4.2.4 on 2024-01-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0013_streamprofilexmppmucs_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamxmppsettings',
            name='conference',
            field=models.TextField(default='', help_text='XMPP Conf Hostname (where Conf objects are created)', verbose_name='XMPP Conference Hostname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamxmppsettings',
            name='pubsub',
            field=models.TextField(default='', help_text='XMPP Pubsub Service Hostname (where Pubsub objects are created)', verbose_name='XMPP Pubsub Hostname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamxmppsettings',
            name='streams',
            field=models.TextField(default='', help_text='XMPP Streams Service Hostname (where Stream objects are created)', verbose_name='XMPP Streams Hostname'),
            preserve_default=False,
        ),
    ]
