# Generated by Django 4.2.4 on 2024-01-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0014_streamxmppsettings_conference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprofilexmppsettings',
            name='create_mucs',
            field=models.BooleanField(default=True, help_text='When enabled, any new stream you create will automatically be assigned a MUC in the XMPP server.', verbose_name='Create MUCs (Multi user Chatrooms) for new streams'),
        ),
        migrations.AddField(
            model_name='streamprofilexmppsettings',
            name='publish_notices',
            field=models.BooleanField(default=True, help_text='When enabled, any stream posts you create on-site will be published via the XMPP service automatically.', verbose_name='Automatically Publish Stream notifications to XMPP'),
        ),
        migrations.AddField(
            model_name='streamprofilexmppsettings',
            name='publish_streams',
            field=models.BooleanField(default=True, help_text='When enabled, any stream posts you create on-site will be published via the XMPP service automatically.', verbose_name='Automatically Publish Stream content to XMPP'),
        ),
        migrations.AddField(
            model_name='streamprofilexmppsettings',
            name='publish_to_groups',
            field=models.BooleanField(default=True, help_text='When enabled, any stream posts you create on-site will be published via the XMPP service to the related groups.', verbose_name='Automatically Publish Stream content to Group XMPP Streams'),
        ),
        migrations.AddField(
            model_name='streamprofilexmppsettings',
            name='pubsub_to_friends',
            field=models.BooleanField(default=True, help_text='When enabled, any content you create is published in streams your friends can follow using an XMPP client.', verbose_name='Enable Publish/Subscribe module for XMPP Friends'),
        ),
        migrations.AlterField(
            model_name='streamxmppsettings',
            name='conference',
            field=models.TextField(help_text='XMPP Conf Hostname (where Conf objects are created): subdomain only!', verbose_name='XMPP Conference Hostname'),
        ),
        migrations.AlterField(
            model_name='streamxmppsettings',
            name='pubsub',
            field=models.TextField(help_text='XMPP Pubsub Service Hostname (where Pubsub objects are created): subdomain only!', verbose_name='XMPP Pubsub Hostname'),
        ),
        migrations.AlterField(
            model_name='streamxmppsettings',
            name='streams',
            field=models.TextField(help_text='XMPP Streams Service Hostname (where Stream objects are created): subdomain only!', verbose_name='XMPP Streams Hostname'),
        ),
    ]
