# Generated by Django 4.0.4 on 2022-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0017_streammessage_posted_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammessage',
            name='contents_text_parsed',
            field=models.TextField(blank=True, null=True, verbose_name='Stream Content: Text Type (Parsed)'),
        ),
    ]
