# Generated by Django 5.0.1 on 2024-06-20 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0018_streamprofilexmppsettings_auto_add_friend_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagesPerNamedStreamView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stream_created", models.DateTimeField(verbose_name="Stream Created")),
                ("stream_type", models.TextField(verbose_name="Stream Type")),
                ("stream_name", models.TextField(verbose_name="Stream Name")),
                (
                    "stream_icon",
                    models.TextField(blank=True, null=True, verbose_name="Stream Icon"),
                ),
                (
                    "stream_shares",
                    models.IntegerField(default=0, verbose_name="Share Count"),
                ),
                (
                    "stream_views",
                    models.IntegerField(default=0, verbose_name="Views Count"),
                ),
                (
                    "stream_nodes",
                    models.IntegerField(default=0, verbose_name="Node Count"),
                ),
                (
                    "stream_archived",
                    models.BooleanField(default=False, verbose_name="Archived FLAG"),
                ),
                (
                    "stream_hidden",
                    models.BooleanField(default=False, verbose_name="Hidden FLAG"),
                ),
                (
                    "stream_system",
                    models.BooleanField(default=False, verbose_name="System FLAG"),
                ),
                ("stream_group_id", models.UUIDField(verbose_name="Stream Group UUID")),
                ("profile_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "profile_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Profile Created"
                    ),
                ),
                (
                    "profile_last_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Profile Last Seen Online"
                    ),
                ),
                (
                    "profile_age",
                    models.TextField(blank=True, default=1, verbose_name="Current Age"),
                ),
                ("profile_name", models.TextField(verbose_name="Name")),
                (
                    "profile_status",
                    models.TextField(
                        blank=True, default="CITIZEN", verbose_name="status"
                    ),
                ),
                (
                    "profile_species",
                    models.TextField(default="Sentient", verbose_name="Species"),
                ),
                (
                    "profile_introduction",
                    models.TextField(verbose_name="Profile Intro"),
                ),
                (
                    "profile_pronouns",
                    models.TextField(max_length=200, verbose_name="Pronouns"),
                ),
                (
                    "profile_gender",
                    models.TextField(max_length=200, verbose_name="Gender"),
                ),
                (
                    "profile_avatar",
                    models.TextField(blank=True, null=True, verbose_name="Avatar URL"),
                ),
                (
                    "profile_posts",
                    models.IntegerField(default=0, verbose_name="Post Count"),
                ),
                (
                    "profile_views",
                    models.IntegerField(default=0, verbose_name="Post Count"),
                ),
                (
                    "profile_nodes",
                    models.IntegerField(default=0, verbose_name="Node Count"),
                ),
                (
                    "profile_blocked",
                    models.BooleanField(default=False, verbose_name="Blocked FLAG"),
                ),
                (
                    "profile_frozen",
                    models.BooleanField(default=False, verbose_name="Frozen FLAG"),
                ),
                (
                    "profile_system",
                    models.BooleanField(default=False, verbose_name="System FLAG"),
                ),
                ("message_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "message_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Stream Created"
                    ),
                ),
                ("message_type", models.TextField(verbose_name="Message Type")),
                (
                    "message_icon",
                    models.TextField(
                        blank=True, null=True, verbose_name="Message Icon"
                    ),
                ),
                (
                    "reposts",
                    models.IntegerField(default=0, verbose_name="Reposts Count"),
                ),
                (
                    "replies",
                    models.IntegerField(default=0, verbose_name="Replies Count"),
                ),
                ("shares", models.IntegerField(default=0, verbose_name="Share Count")),
                ("likes", models.IntegerField(default=0, verbose_name="Like Count")),
                (
                    "threads",
                    models.IntegerField(default=0, verbose_name="Thread Count"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Views Count")),
                (
                    "contents_text",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Stream Content: Text Type",
                    ),
                ),
                (
                    "contents_text_parsed",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Stream Content: Text Type (Parsed)",
                    ),
                ),
                (
                    "contents_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Stream Content: JSON Type"
                    ),
                ),
                (
                    "contents_bin",
                    models.BinaryField(
                        blank=True,
                        null=True,
                        verbose_name="Stream Content: Binary Type",
                    ),
                ),
            ],
            options={
                "db_table": "communities_stream_named_message_view",
                "managed": False,
            },
        ),
    ]
