# Generated by Django 4.0.4 on 2022-08-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0019_messagesperstreamview'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Stream Name'),
        ),
        migrations.AddField(
            model_name='stream',
            name='tag',
            field=models.TextField(blank=True, null=True, verbose_name='Stream Tag'),
        ),
    ]
