# Generated by Django 4.0.4 on 2022-08-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0021_streamtype_streamtype_unique_stream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='streamtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='stream.streamtype', verbose_name='Stream Type (public)'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='type',
            field=models.TextField(verbose_name='Stream Type (internal)'),
        ),
    ]
