# Generated by Django 4.0.4 on 2022-08-31 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
        ('stream', '0025_stream_unique_stream_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group'),
        ),
    ]
