# Generated by Django 4.2.4 on 2023-08-15 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_initial'),
        ('group', '0002_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataTotals',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Billing Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Billing Updated')),
                ('period_start', models.DateTimeField(auto_now_add=True, verbose_name='Billing Period Start')),
                ('period_end', models.DateTimeField(auto_now_add=True, verbose_name='Billing Period End')),
                ('category', models.TextField(verbose_name='Billing Category')),
                ('category_items', models.IntegerField(default=0, verbose_name='Billing category items')),
                ('category_bytes', models.FloatField(default=0, verbose_name='Billing category bytes')),
                ('category_xfer_bytes', models.FloatField(default=0, verbose_name='Billing category transferred bytes')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'core_metrics_user_data_totals',
            },
        ),
        migrations.CreateModel(
            name='UserDataEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Billing Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Billing Updated')),
                ('category', models.TextField(verbose_name='Billing Category')),
                ('reference', models.TextField(verbose_name='Billing Reference')),
                ('bytes', models.FloatField(default=0, verbose_name='Billing category bytes')),
                ('xfer_bytes', models.FloatField(default=0, verbose_name='Billing category transferred bytes')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'core_metrics_user_data_entry',
            },
        ),
        migrations.CreateModel(
            name='ProfilePageHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.profile', verbose_name='Parent')),
            ],
            options={
                'db_table': 'core_metrics_profile_page_hit_totals',
            },
        ),
        migrations.CreateModel(
            name='ProfilePageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.profile', verbose_name='Parent')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
            options={
                'db_table': 'core_metrics_profile_page_hit',
            },
        ),
        migrations.CreateModel(
            name='ProfileIndexPageHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
            ],
            options={
                'db_table': 'core.metrics.profile_index_page_hit_totals',
            },
        ),
        migrations.CreateModel(
            name='ProfileIndexPageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('visistor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
            options={
                'db_table': 'core.metrics.profile_index_page_hit',
            },
        ),
        migrations.CreateModel(
            name='GroupPageHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Parent')),
            ],
            options={
                'db_table': 'core_metrics_group_page_hit_totals',
            },
        ),
        migrations.CreateModel(
            name='GroupPageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('visistor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
            options={
                'db_table': 'core_metrics_group_page_hit',
            },
        ),
        migrations.CreateModel(
            name='GroupDataTotals',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Billing Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Billing Updated')),
                ('period_start', models.DateTimeField(auto_now_add=True, verbose_name='Billing Period Start')),
                ('period_end', models.DateTimeField(auto_now_add=True, verbose_name='Billing Period End')),
                ('category', models.TextField(verbose_name='Billing Category')),
                ('category_items', models.IntegerField(default=0, verbose_name='Billing category items')),
                ('category_bytes', models.FloatField(default=0, verbose_name='Billing category bytes')),
                ('category_xfer_bytes', models.FloatField(default=0, verbose_name='Billing category transferred bytes')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Group')),
            ],
            options={
                'db_table': 'core_metrics_group_data_totals',
            },
        ),
        migrations.CreateModel(
            name='GalleryProfilePageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.profile', verbose_name='Parent')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
            options={
                'db_table': 'core_metrics_gallery_profile_page_hit',
            },
        ),
        migrations.CreateModel(
            name='GalleryItemHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.galleryitem', verbose_name='Item')),
            ],
            options={
                'db_table': 'core_metrics_gallery_item_himt_totals',
            },
        ),
        migrations.CreateModel(
            name='GalleryItemHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Item Hit Type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Item viewed by member of group')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.galleryitem', verbose_name='Item')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Item Viewed by Profile')),
            ],
            options={
                'db_table': 'core_metrics_gallery_item_hit',
            },
        ),
        migrations.CreateModel(
            name='GalleryHomePageHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
            ],
            options={
                'db_table': 'core_metrics_gallery_home_page_hit_totals',
            },
        ),
        migrations.CreateModel(
            name='GalleryHomePageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('visistor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
            options={
                'db_table': 'core_metrics_gallery_home_page_hit',
            },
        ),
        migrations.CreateModel(
            name='GalleryCollectionPageHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gallerycollection', verbose_name='Parent')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
            ],
            options={
                'db_table': 'core_metrics_gallery_collection_page_hit_totals',
            },
        ),
        migrations.CreateModel(
            name='GalleryCollectionPageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gallerycollection', verbose_name='Collection')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
            options={
                'db_table': 'core_metrics_gallery_collection_page_hit',
            },
        ),
        migrations.CreateModel(
            name='CommunityPageHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
            ],
            options={
                'db_table': 'core_metrics_community_page_hit_totals',
            },
        ),
        migrations.CreateModel(
            name='CommunityPageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('visistor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
            options={
                'db_table': 'core_metrics_community_page_hit',
            },
        ),
    ]
