# Generated by Django 4.2.4 on 2023-08-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profileindexpagehit',
            table='core_metrics_profile_index_page_hit',
        ),
        migrations.AlterModelTable(
            name='profileindexpagehittotals',
            table='core_metrics_profile_index_page_hit_totals',
        ),
    ]
