# Generated by Django 4.0.2 on 2022-04-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
        ('profiles', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitemhit',
            old_name='updated',
            new_name='created',
        ),
        migrations.AddField(
            model_name='galleryitemhit',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address'),
        ),
        migrations.AddField(
            model_name='galleryitemhit',
            name='user_agent',
            field=models.TextField(db_index=True, default='', verbose_name='Hit User Agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryitemhit',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Item viewed by member of group'),
        ),
        migrations.AlterField(
            model_name='galleryitemhit',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Item Viewed by Profile'),
        ),
    ]
