# Generated by Django 4.0.2 on 2022-04-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('profiles', '0001_initial'),
        ('group', '0002_initial'),
        ('metrics', '0007_communitypagehittotals_communitypagehit'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypagehit',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address'),
        ),
        migrations.AddField(
            model_name='communitypagehit',
            name='user_agent',
            field=models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent'),
        ),
        migrations.AddField(
            model_name='grouppagehit',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address'),
        ),
        migrations.AddField(
            model_name='grouppagehit',
            name='user_agent',
            field=models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent'),
        ),
        migrations.CreateModel(
            name='GalleryHomePageHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryHomePageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('visistor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
        ),
    ]
