# Generated by Django 4.2.4 on 2023-08-15 20:52

from django.db import migrations, models
import django.db.models.deletion
import martor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlmanacMenuCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.TextField(max_length=200, unique=True, verbose_name='MenuCat ID')),
                ('icon', models.TextField(max_length=200, verbose_name='MenuCat Icon')),
                ('title', models.TextField(max_length=200, verbose_name='MenuCat Title')),
                ('order', models.IntegerField(default=0, verbose_name='Order Count')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'content_manager_almanac_menu_category',
            },
        ),
        migrations.CreateModel(
            name='AlmanacMenuCategoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order Count')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'content_manager_almanac_menu_category_entry',
            },
        ),
        migrations.CreateModel(
            name='AlmanacPage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.TextField(max_length=200, unique=True, verbose_name='Page ID')),
                ('title', models.TextField(max_length=200, verbose_name='Page Title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Page Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Page Updated')),
                ('introduction', models.TextField(verbose_name='Page Intro')),
                ('avatar', models.TextField(blank=True, null=True, verbose_name='Avatar URL')),
                ('posts', models.IntegerField(default=0, verbose_name='Post Count')),
                ('views', models.IntegerField(default=0, verbose_name='View Count')),
                ('nodes', models.IntegerField(default=0, verbose_name='Node Count')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'content_manager_almanac_page',
            },
        ),
        migrations.CreateModel(
            name='AlmanacPageText',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Page Text Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Page Updated')),
                ('language', models.TextField(default='en-US', max_length=5, verbose_name='Page Language')),
                ('page_contents', martor.models.MartorField(verbose_name='Page Contents')),
                ('current', models.BooleanField(default=False, verbose_name='current FLAG')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almanac.almanacpage', verbose_name='AlmanacPage')),
            ],
            options={
                'db_table': 'content_manager_almanac_page_text',
            },
        ),
    ]
