# Generated by Django 3.2.9 on 2021-11-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField(max_length=200, verbose_name='Community Hash')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Profile Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Profile Updated')),
                ('name', models.TextField(verbose_name='Name')),
                ('posts', models.IntegerField(default=0, verbose_name='Post Count')),
                ('profile', models.IntegerField(default=0, verbose_name='Profile Count')),
                ('group', models.IntegerField(default=0, verbose_name='Group Count')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
        ),
        migrations.CreateModel(
            name='VHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='VHost Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='VHost Updated')),
                ('hostname', models.TextField(max_length=200, null=True, verbose_name='VHost Hostname')),
                ('ipaddr', models.GenericIPAddressField(null=True, verbose_name='VHost IP address')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community to Apply to VHOST')),
            ],
        ),
    ]
