# Generated by Django 3.2.9 on 2021-11-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupkeywords'),
        ('community', '0002_communitygroups_communityprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityGroups',
            new_name='CommunityGroup',
        ),
    ]
