# Generated by Django 3.2.9 on 2021-11-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_communitygroups_communitygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='avatar',
            field=models.TextField(default='', verbose_name='Avatar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='tagline',
            field=models.TextField(default='', verbose_name='Tagline'),
            preserve_default=False,
        ),
    ]
