# Generated by Django 3.2.9 on 2021-11-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20211116_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='avatar',
            field=models.TextField(null=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='community',
            name='tagline',
            field=models.TextField(null=True, verbose_name='Tagline'),
        ),
    ]
