# Generated by Django 4.0.4 on 2022-08-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_profilepagenodes_profilepagenode'),
        ('community', '0005_friend_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile'),
        ),
    ]
