# Generated by Django 3.2.9 on 2021-11-18 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20211116_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='id',
        ),
        migrations.AddField(
            model_name='community',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
