# Generated by Django 3.2.9 on 2021-11-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20211118_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vhost',
            old_name='community',
            new_name='community_old',
        ),
    ]
