# Generated by Django 3.2.9 on 2021-11-18 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_rename_community_vhost_community_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vhost',
            name='community_old',
        ),
        migrations.AddField(
            model_name='vhost',
            name='community',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community to Apply to VHOST'),
        ),
    ]
