# Generated by Django 4.0.2 on 2022-02-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20211118_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityprofile',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='profile',
        ),
    ]
