# Generated by Django 4.0.2 on 2022-02-12 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_profile_status'),
        ('community', '0009_remove_communityprofile_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='User'),
        ),
    ]
