# Generated by Django 4.0.2 on 2022-02-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_communityprofile_community_communityprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitygroup',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitygroup',
            name='group',
        ),
    ]
