# Generated by Django 4.0.2 on 2022-02-12 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_groupmember_primary'),
        ('community', '0011_remove_communitygroup_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group'),
        ),
    ]
