# Generated by Django 4.0.2 on 2022-02-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0012_alter_pagewidget_banner_alter_pagewidget_footer_and_more'),
        ('community', '0012_communitygroup_community_communitygroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='dynapage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dynapages.page'),
        ),
    ]
