# Generated by Django 4.0.2 on 2022-02-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_community_dynapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='action_call_cover',
            field=models.TextField(default='', verbose_name='Action Call for Cover page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='introduction',
            field=models.TextField(default='', verbose_name='Introduction'),
            preserve_default=False,
        ),
    ]
