# Generated by Django 4.0.2 on 2022-02-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_vhost_restricted_communityadmins'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityadmins',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active FLAG'),
        ),
    ]
