# Generated by Django 4.0.2 on 2022-04-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_communityadmins_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='restricted',
            field=models.BooleanField(default=False, verbose_name='Restricted Join Mode FLAG'),
        ),
    ]
