# Generated by Django 4.0.2 on 2022-04-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0060_galleryitemcomments_item'),
        ('community', '0017_community_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='backgroundItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gallery.galleryitem'),
        ),
    ]
