# Generated by Django 4.0.4 on 2022-05-31 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_timezone_preferences_messages_top_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.TextField(default='default', verbose_name='Theme ID')),
                ('name', models.TextField(default='Ply Default Theme', verbose_name='Theme Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.AlterField(
            model_name='timezone',
            name='offset',
            field=models.TextField(default='-05:00', verbose_name='TimeZone Code'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='preferences.theme', verbose_name='System Theme'),
        ),
    ]
