# Generated by Django 4.0.4 on 2022-05-31 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_theme_alter_timezone_offset_alter_preferences_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='preferences.timezone', verbose_name='TimeZone Code'),
        ),
    ]
