# Generated by Django 4.0.4 on 2022-05-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_alter_preferences_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='preferences.theme', verbose_name='System Theme'),
        ),
    ]
