# Generated by Django 4.0.4 on 2022-05-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_alter_preferences_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='longdate',
            field=models.TextField(default='%c', max_length=50, verbose_name='Long Date Format for Output'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='shortdate',
            field=models.TextField(default='%x', max_length=50, verbose_name='Short Date Time Format for Output'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='time',
            field=models.TextField(default='%I:%M:%S', max_length=50, verbose_name='Time Format for Output'),
        ),
    ]
