""" Introducing a static, off-settings Version tracking mechanism:"""
PLY_VERSION_DATABASE = 2024
PLY_VERSION_FEATURESET_MAJOR = 0x7e8
PLY_VERSION_FEATURESET_MINOR = 0x3f2
PLY_VERSION_MAJOR = 0x7e8
PLY_VERSION_MINOR = 0xf2
PLY_VERSION_MINOR_CODE = "0310"
PLY_VERSION_MINOR_PATCH ="a2"
PLY_VERSION_DEV = True


