# Generated by Django 4.0.4 on 2022-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mentions',
            field=models.IntegerField(default=0, verbose_name='Mention Count'),
        ),
        migrations.AddField(
            model_name='profile',
            name='messages',
            field=models.IntegerField(default=0, verbose_name='Message Count'),
        ),
    ]
