# Generated by Django 4.0.4 on 2022-08-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_dashboard dynapage node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Dashboard Dynapage Node',
        ),
    ]
