# Generated by Django 4.0.4 on 2022-08-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0011_templates_app'),
        ('profiles', '0008_profilepagenodes_unique_dynapage_node'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePageNodes',
            new_name='ProfilePageNode',
        ),
    ]
