# Generated by Django 4.2.4 on 2023-10-23 20:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ufls_furry_department',
            },
        ),
        migrations.CreateModel(
            name='EmailValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('used', models.BooleanField(default=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('usedFor', models.CharField(default='Generic', max_length=100)),
            ],
            options={
                'db_table': 'ufls_furry_email_validation',
            },
        ),
        migrations.CreateModel(
            name='RoomMonitor',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ufls_furry_room_monitor',
            },
        ),
        migrations.CreateModel(
            name='RoomMonitorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furry.roommonitor')),
            ],
            options={
                'db_table': 'ufls_furry_room_monitor_history',
            },
        ),
        migrations.CreateModel(
            name='RegistrantAssociationKey',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'db_table': 'ufls_furry_registrant_association_key',
            },
        ),
    ]
