# Generated by Django 3.1.7 on 2021-05-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
