# Generated by Django 4.2.4 on 2023-10-23 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('furry', '0001_initial'),
        ('registrar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantassociationkey',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.registrantdata'),
        ),
        migrations.AddField(
            model_name='emailvalidation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
