# Generated by Django 3.1.7 on 2021-05-09 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('furry', '0003_emailvalidation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_me',
            new_name='emailMe',
        ),
        migrations.AddField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 0, 17, 46, 120748, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
    ]
