# Generated by Django 3.1.7 on 2021-05-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furry', '0004_auto_20210508_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferredName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
