# Generated by Django 3.1.7 on 2021-05-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furry', '0005_auto_20210508_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='staffBoardMember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_member_responsible', to='furry.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='staffManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_staff_report', to='furry.profile'),
        ),
    ]
