# Generated by Django 3.2.4 on 2021-12-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furry', '0007_auto_20210515_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalidation',
            name='usedFor',
            field=models.CharField(default='Legacy', max_length=100),
            preserve_default=False,
        ),
    ]
