# Generated by Django 3.2.4 on 2021-12-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furry', '0008_emailvalidation_usedfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalidation',
            name='usedFor',
            field=models.CharField(default='Generic', max_length=100),
        ),
    ]
