# Generated by Django 3.2.4 on 2022-02-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furry', '0009_alter_emailvalidation_usedfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMonitor',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMonitorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furry.roommonitor')),
            ],
        ),
    ]
