# Generated by Django 3.2.4 on 2022-04-06 00:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20220405_1823'),
        ('furry', '0010_roommonitor_roommonitorhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrantAssociationKey',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furry.profile')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrantdata')),
            ],
        ),
    ]
