# Generated by Django 3.2.9 on 2021-11-18 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_groupkeywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataTotals',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Billing Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Billing Updated')),
                ('period_start', models.DateTimeField(auto_now_add=True, verbose_name='Billing Period Start')),
                ('period_end', models.DateTimeField(auto_now_add=True, verbose_name='Billing Period End')),
                ('category', models.TextField(verbose_name='Billing Category')),
                ('category_items', models.IntegerField(default=0, verbose_name='Billing category items')),
                ('category_bytes', models.FloatField(default=0, verbose_name='Billing category bytes')),
                ('category_xfer_bytes', models.FloatField(default=0, verbose_name='Billing category transferred bytes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDataTotals',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Billing Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Billing Updated')),
                ('period_start', models.DateTimeField(auto_now_add=True, verbose_name='Billing Period Start')),
                ('period_end', models.DateTimeField(auto_now_add=True, verbose_name='Billing Period End')),
                ('category', models.TextField(verbose_name='Billing Category')),
                ('category_items', models.IntegerField(default=0, verbose_name='Billing category items')),
                ('category_bytes', models.FloatField(default=0, verbose_name='Billing category bytes')),
                ('category_xfer_bytes', models.FloatField(default=0, verbose_name='Billing category transferred bytes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='User')),
            ],
        ),
    ]
