# Generated by Django 3.2.9 on 2021-11-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupkeywords'),
        ('profiles', '0013_profile_slug'),
        ('gallery', '0026_galleryitem_profile'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdatatotals',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Group'),
        ),
        migrations.CreateModel(
            name='GalleryItemHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Item Hit Type')),
                ('visited', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Item viewed by member of group')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem', verbose_name='Item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Item Viewed by Profile')),
            ],
        ),
    ]
