# Generated by Django 4.0.2 on 2022-04-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_rename_updated_galleryitemhit_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitemhit',
            name='user_agent',
            field=models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent'),
        ),
    ]
