# Generated by Django 3.2.9 on 2021-11-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20211118_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitemhit',
            old_name='visited',
            new_name='updated',
        ),
    ]
