# Generated by Django 3.2.9 on 2021-11-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_slug'),
        ('community', '0005_auto_20211116_0144'),
        ('group', '0002_groupkeywords'),
        ('metrics', '0003_rename_visited_galleryitemhit_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitemhit',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupdatatotals',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdatatotals',
            name='community',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProfilePageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
        ),
    ]
