# Generated by Django 4.0.2 on 2022-04-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
        ('profiles', '0001_initial'),
        ('metrics', '0003_alter_galleryitemhit_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitemhit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Item viewed by member of group'),
        ),
        migrations.AlterField(
            model_name='galleryitemhit',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Item Viewed by Profile'),
        ),
    ]
