# Generated by Django 3.2.9 on 2021-11-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20211118_2046'),
        ('group', '0003_auto_20211118_2043'),
        ('gallery', '0026_galleryitem_profile'),
        ('profiles', '0013_profile_slug'),
        ('metrics', '0005_auto_20211118_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePageHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.profile', verbose_name='Parent')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPageHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Parent')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItemHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem', verbose_name='Item')),
            ],
        ),
    ]
