# Generated by Django 4.0.2 on 2022-04-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_initial'),
        ('community', '0002_initial'),
        ('group', '0002_initial'),
        ('profiles', '0001_initial'),
        ('metrics', '0005_rename_updated_profilepagehit_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryProfilePageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.profile', verbose_name='Parent')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCollectionPageHitTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('totals', models.IntegerField(default=0, verbose_name='Total views')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycollection', verbose_name='Parent')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCollectionPageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(db_index=True, verbose_name='Hit Type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('user_agent', models.TextField(blank=True, db_index=True, verbose_name='Hit User Agent')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycollection', verbose_name='Collection')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='viewed by member of group')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.profile', verbose_name='Viewed by Profile')),
            ],
        ),
    ]
