# Generated by Django 3.2.9 on 2021-11-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_galleryitemhittotals_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppagehit',
            old_name='profile',
            new_name='visistor',
        ),
    ]
