# Generated by Django 3.2.9 on 2021-12-02 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0008_auto_20211118_2107'),
        ('metrics', '0008_rename_profile_grouppagehit_visistor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Billing Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Billing Updated')),
                ('category', models.TextField(verbose_name='Billing Category')),
                ('bytes', models.FloatField(default=0, verbose_name='Billing category bytes')),
                ('xfer_bytes', models.FloatField(default=0, verbose_name='Billing category transferred bytes')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='community.community', verbose_name='Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
