# Generated by Django 3.2.9 on 2021-12-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_userdataentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataentry',
            name='reference',
            field=models.TextField(default='', verbose_name='Billing Reference'),
            preserve_default=False,
        ),
    ]
