# Generated by Django 4.0.4 on 2022-05-26 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_profile_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceRoll',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Roll Time')),
                ('type', models.TextField(verbose_name='Roll Type')),
                ('count', models.IntegerField(default=1, verbose_name='Dice Count')),
                ('sides', models.IntegerField(default=12, verbose_name='Number of Sides')),
                ('result', models.IntegerField(default=0, verbose_name='Results ')),
                ('threshold', models.IntegerField(default=6, verbose_name='Threshold ')),
                ('contents_json', models.JSONField(blank=True, null=True, verbose_name='Verbose Roll Data')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Author')),
            ],
        ),
    ]
