# Generated by Django 4.0.4 on 2022-08-11 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_profilepagenodes_profilepagenode'),
        ('community', '0005_friend_community'),
        ('plydice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Event Created')),
                ('type', models.TextField(verbose_name='Event Type')),
                ('count', models.IntegerField(default=1, verbose_name='Dice Count')),
                ('sides', models.IntegerField(default=12, verbose_name='Number of Sides')),
                ('contents_json', models.JSONField(blank=True, null=True, verbose_name='Verbose Event Data')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Author')),
            ],
        ),
        migrations.AddField(
            model_name='diceroll',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diceroll',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.CreateModel(
            name='DiceEventRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plydice.diceevent', verbose_name='Community')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plydice.diceroll', verbose_name='Community')),
            ],
        ),
        migrations.AddConstraint(
            model_name='diceeventroll',
            constraint=models.UniqueConstraint(fields=('event', 'roll'), name='unique_roll'),
        ),
    ]
