# Generated by Django 4.0.4 on 2022-08-19 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plydice', '0002_diceevent_diceroll_community_alter_diceroll_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diceeventroll',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plydice.diceevent', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='diceeventroll',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plydice.diceroll', verbose_name='Roll'),
        ),
    ]
