# Generated by Django 3.1.3 on 2022-05-07 21:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='queues',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mainqueue', 'Badge Printer - Main Queue'), ('minor15queue', 'Badge Printer - Minor 15+ Queue'), ('minor14queue', 'Badge Printer - Minor 14-15 Queue'), ('daypassqueue', 'Badge Printer - Day Pass Queue'), ('dealersdenqueue', 'Badge Printer - Dealers Den Queue'), ('blackonly', 'Badge Printer - Black Prints Only'), ('r-frontreg1', 'Receipt Printer - Front of Reg Station 1 Queue'), ('r-frontreg2', 'Receipt Printer - Front of Reg Station 2 Queue'), ('r-frontreg3', 'Receipt Printer - Front of Reg Station 3 Queue'), ('r-frontreg4', 'Receipt Printer - Front of Reg Station 4 Queue'), ('r-frontreg5', 'Receipt Printer - Front of Reg Station 5 Queue'), ('r-frontreg', 'Receipt Printer - Front of Reg Station General Queue'), ('r-backreg', 'Receipt Printer - Back of Reg Picker Station Queue'), ('l-it', 'Label Printer - IT Label Printer Queue')], max_length=500),
        ),
    ]
