version: "3.2"
services:

  #ply:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: ply_system_setup
  #

  ply_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - ply_net

networks:
  ply_net:
    driver: bridge