# Generated by Django 4.2.4 on 2023-08-15 20:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Relationship Created')),
                ('type', models.TextField(verbose_name='Notification Type')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Notification Icon')),
                ('contents_text', models.TextField(blank=True, null=True, verbose_name='Notification Content: Text Type')),
                ('contents_json', models.JSONField(blank=True, null=True, verbose_name='Notification Content: JSON Type')),
                ('contents_bin', models.BinaryField(blank=True, null=True, verbose_name='Notification Content: Binary Type')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile')),
            ],
            options={
                'db_table': 'communities_notifications_notifications',
            },
        ),
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Mention Inbox Created')),
                ('opened', models.DateTimeField(blank=True, null=True, verbose_name='Mention has been opened')),
                ('replied', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Mention has been replied to')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted FLAG')),
                ('deleted_on', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Mention Inbox Deleted on')),
                ('type', models.TextField(verbose_name='Mention Type')),
                ('contents_text', models.TextField(blank=True, null=True, verbose_name='Mention Content: Text Type')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Recipient Profile')),
            ],
            options={
                'db_table': 'communities_notifications_mentions',
            },
        ),
        migrations.CreateModel(
            name='NotificationInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Notification Inbox Created')),
                ('opened', models.DateTimeField(blank=True, null=True, verbose_name='Notification has been opened')),
                ('replied', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Notification has been replied to')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted FLAG')),
                ('deleted_on', models.DateTimeField(editable=False, null=True, verbose_name='Notification Inbox Deleted on')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification', verbose_name='Notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Recipient Profile')),
            ],
            options={
                'db_table': 'communities_notifications_notification_inbox',
                'unique_together': {('notification', 'community', 'recipient')},
            },
        ),
    ]
