# Generated by Django 4.0.2 on 2022-05-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationinbox_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationinbox',
            name='deleted_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Notification Inbox Deleted on'),
        ),
    ]
