# Generated by Django 4.0.2 on 2022-05-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationinbox_deleted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='processed',
        ),
    ]
