# Generated by Django 4.0.4 on 2022-05-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_notifications'),
        ('community', '0005_friend_community'),
        ('notifications', '0005_remove_notification_delivered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Mention Inbox Created')),
                ('opened', models.DateTimeField(blank=True, null=True, verbose_name='Mention has been opened')),
                ('replied', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Mention has been replied to')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted FLAG')),
                ('deleted_on', models.DateTimeField(editable=False, null=True, verbose_name='Mention Inbox Deleted on')),
                ('type', models.TextField(verbose_name='Mention Type')),
                ('contents_text', models.TextField(blank=True, null=True, verbose_name='Mention Content: Text Type')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Recipient Profile')),
            ],
        ),
    ]
