# Generated by Django 4.0.4 on 2022-05-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_mentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentions',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted FLAG'),
        ),
        migrations.AlterField(
            model_name='mentions',
            name='deleted_on',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Mention Inbox Deleted on'),
        ),
    ]
