# Generated by Django 4.0.4 on 2022-06-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('hash', 'discipline'), name='unique_hashdis'),
        ),
    ]
