from ufls import settings

"""
Django settings for ufls project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import django_heroku, os
from dotenv import load_dotenv
from datetime import timedelta

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_ROOT = settings.STATIC_ROOT


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings.DEBUG

ALLOWED_HOSTS = ['localhost','0.0.0.0']


# Application definition

INSTALLED_APPS = settings.INSTALLED_APPS

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

CELERY_RESULT_BACKEND = settings.CELERY_RESULT_BACKEND
CELERY_CACHE_BACKEND = settings.CELERY_CACHE_BACKEND
CELERY_BROKER_URL = settings.CELERY_BROKER_URL
CELERY_TIMEZONE = settings.CELERY_TIMEZONE
CELERY_TASK_TRACK_STARTED = settings.CELERY_TASK_TRACK_STARTED
CELERY_TASK_TIME_LIMIT = settings.CELERY_TASK_TIME_LIMIT

CELERY_TASK_ROUTES = settings.CELERY_TASK_TIME_LIMIT

REST_FRAMEWORK = settings.REST_FRAMEWORK

MIDDLEWARE = settings.MIDDLEWARE

CORS_ALLOWED_ORIGINS = settings.CORS_ALLOWED_ORIGINS

STATICFILES_STORAGE = settings.STATICFILES_STORAGE

ROOT_URLCONF = settings.ROOT_URLCONF

TEMPLATES = settings.TEMPLATES

WSGI_APPLICATION = settings.WSGI_APPLICATION


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = settings.AUTH_PASSWORD_VALIDATORS


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = settings.LANGUAGE_CODE

TIME_ZONE = settings.TIME_ZONE

USE_I18N = settings.USE_I18N

USE_L10N = settings.USE_L10N

USE_TZ = settings.USE_TZ


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = settings.STATIC_URL
LOGIN_URL = settings.LOGIN_URL

AUTH_SERVER = settings.AUTH_SERVER
AUTH_CLIENT_ID = settings.AUTH_CLIENT_ID
AUTH_CLIENT_SECRET = settings.AUTH_CLIENT_SECRET

AUTH_SCOPE = settings.AUTH_SCOPE

AUTHENTICATION_BACKENDS = settings.AUTHENTICATION_BACKENDS

AUTH_GET_USER_FUNCTION = settings.AUTH_GET_USER_FUNCTION
ALLOWED_REDIRECTION_HOSTS = settings.ALLOWED_REDIRECTION_HOSTS

EMAIL_HOST = settings.EMAIL_HOST
EMAIL_PORT = settings.EMAIL_PORT
EMAIL_HOST_USER = settings.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = settings.EMAIL_HOST_PASSWORD
EMAIL_USE_TLS = settings.EMAIL_USE_TLS
DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL
#EMAIL_USE_SSL = True

sentry_sdk.init(
    dsn="https://5af91051bb2642319c692af3975fc216@o334180.ingest.sentry.io/5899241",
    integrations=[DjangoIntegration()],

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)

#must be at bottom
#django_heroku.settings(locals())
