# Generated by Django 4.2.4 on 2023-08-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Message Created')),
                ('recieved', models.DateTimeField(editable=False, null=True, verbose_name='Message Recieved')),
                ('opened', models.DateTimeField(editable=False, null=True, verbose_name='Message Opened')),
                ('read', models.DateTimeField(editable=False, null=True, verbose_name='Message Read')),
                ('type', models.TextField(max_length=200, verbose_name='Message Type')),
                ('subject', models.TextField(verbose_name='Message subject')),
                ('slug', models.TextField(verbose_name='Message Hash Slug')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'roleplaying_comms_message',
            },
        ),
        migrations.CreateModel(
            name='MessageContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(editable=False, null=True, verbose_name='Recieved')),
                ('contents', models.TextField(verbose_name='Message Contents')),
                ('attach', models.TextField(verbose_name='Message Attachments')),
            ],
            options={
                'db_table': 'roleplaying_comms_message_contents',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Notification Created')),
                ('recieved', models.DateTimeField(editable=False, null=True, verbose_name='Notification Recieved')),
                ('opened', models.DateTimeField(editable=False, null=True, verbose_name='Notification Opened')),
                ('read', models.DateTimeField(editable=False, null=True, verbose_name='Notification Read')),
                ('type', models.TextField(max_length=200, verbose_name='Notification Type')),
                ('label', models.TextField(verbose_name='Notification Label')),
                ('slug', models.TextField(verbose_name='Notification Hash Slug')),
                ('contents', models.TextField(verbose_name='Notification Contents')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'roleplaying_comms_notifications',
            },
        ),
    ]
