# Generated by Django 4.2.4 on 2024-03-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlyApplication",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
