# Generated by Django 4.2.4 on 2024-03-07 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ply", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plyapplication",
            name="app_module",
            field=models.TextField(
                default="", unique=True, verbose_name="Application Module"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plyapplication",
            name="app_name",
            field=models.TextField(
                default="", unique=True, verbose_name="Application Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plyapplication",
            name="installed",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date Installed",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plyapplication",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
        ),
        migrations.AddField(
            model_name="plyapplication",
            name="version_major",
            field=models.TextField(
                default="", verbose_name="Application Module Major Version"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plyapplication",
            name="version_minor",
            field=models.TextField(
                default="", verbose_name="Application Module Minor Version"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plyapplication",
            name="version_release",
            field=models.TextField(
                default="", verbose_name="Application Module Release Version"
            ),
            preserve_default=False,
        ),
    ]
