# Generated by Django 5.0.1 on 2024-09-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ply", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plyapplication",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
