# Generated by Django 4.2.4 on 2024-03-07 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ply", "0002_plyapplication_app_module_plyapplication_app_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlyApplicationVersionHistory",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "old_version_string",
                    models.TextField(verbose_name="Application Old Version String"),
                ),
                (
                    "new_version_string",
                    models.TextField(verbose_name="Application New Version String"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ply.plyapplication",
                        verbose_name="Ply Application",
                    ),
                ),
            ],
        ),
    ]
