# Generated by Django 4.2.4 on 2024-03-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ply", "0003_plyapplicationversionhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plyapplication",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Date Updated"
            ),
        ),
    ]
