# Generated by Django 4.2.4 on 2024-03-07 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ply", "0004_alter_plyapplication_updated"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="plyapplication",
            table="ply.application",
        ),
        migrations.AlterModelTable(
            name="plyapplicationversionhistory",
            table="ply.application_version_history",
        ),
    ]
