# Generated by Django 4.2.4 on 2024-03-07 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ply", "0005_alter_plyapplication_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="plyapplication",
            table="ply_application",
        ),
        migrations.AlterModelTable(
            name="plyapplicationversionhistory",
            table="ply_application_version_history",
        ),
    ]
