# Generated by Django 5.0.1 on 2024-03-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ply', '0006_alter_plyapplication_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyapplication',
            name='app_name',
            field=models.TextField(blank=True, verbose_name='Application Name'),
        ),
        migrations.AlterField(
            model_name='plyapplication',
            name='version_major',
            field=models.TextField(default='0', verbose_name='Application Module Major Version'),
        ),
        migrations.AlterField(
            model_name='plyapplication',
            name='version_minor',
            field=models.TextField(default='0', verbose_name='Application Module Minor Version'),
        ),
        migrations.AlterField(
            model_name='plyapplication',
            name='version_release',
            field=models.TextField(default='0', verbose_name='Application Module Release Version'),
        ),
    ]
