# Generated by Django 5.0.1 on 2024-03-07 02:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ply', '0007_alter_plyapplication_app_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyapplication',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID, primary_key=True, serialize=False),
        ),
    ]
