# Generated by Django 5.0.1 on 2024-03-07 02:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ply', '0008_alter_plyapplication_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyapplication',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
