# Generated by Django 5.0.1 on 2024-03-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ply', '0010_alter_plyapplicationversionhistory_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plyapplication',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Updated'),
        ),
    ]
