# Generated by Django 5.0.1 on 2024-03-07 03:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ply', '0011_alter_plyapplication_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlyApplicationDashboardType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.TextField(verbose_name='Dashboard Type')),
                ('default', models.BooleanField(default=False, verbose_name='Default Dashboard Type')),
                ('active', models.BooleanField(default=True, verbose_name=' Dashboard Type Active')),
                ('privileged', models.BooleanField(default=False, verbose_name='Default Type Privileged')),
                ('descr', models.TextField(verbose_name='Dashboard Type Description')),
                ('menu_class', models.TextField(verbose_name='Dashboard Type Menu Class Name')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ply.plyapplication', verbose_name='Ply Application')),
            ],
            options={
                'db_table': 'ply_application_dashboard_type',
                'unique_together': {('application', 'type')},
            },
        ),
    ]
