# Generated by Django 5.0.1 on 2024-03-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ply', '0012_plyapplicationdashboardtype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plyapplicationdashboardtype',
            unique_together={('application', 'mode')},
        ),
        migrations.AddField(
            model_name='plyapplicationdashboardtype',
            name='mode',
            field=models.TextField(default='', verbose_name='Dashboard Mode'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='plyapplicationdashboardtype',
            name='type',
        ),
    ]
