# Generated by Django 5.0.1 on 2024-03-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ply', '0013_alter_plyapplicationdashboardtype_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlyApplicationDashboardType',
        ),
    ]
