# Generated by Django 3.2.4 on 2021-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_asset_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('AP', 'Access Point'), ('BX', 'Box'), ('CA', 'Card Printer'), ('CH', 'Chromebook'), ('CP', 'Computer'), ('LO', 'Loaned Hardware'), ('OT', 'Other'), ('PR', 'Traditional Printer'), ('RD', 'Radio'), ('SV', 'Server'), ('SW', 'Networking Switch'), ('TB', 'Tablet')], max_length=2),
        ),
    ]
