# Generated by Django 3.2.4 on 2021-07-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('danger', 'Checked In - Stored'), ('warning', 'Checked Out - On Long Term Loan'), ('primary', 'Checked In - Ready for Use'), ('secondary', 'In Transit - Transporting'), ('success', 'Checked Out - In Use'), ('dark', 'Decommissioned')], default='primary', max_length=15),
        ),
    ]
