# Generated by Django 3.2.4 on 2021-08-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
