# Generated by Django 3.1.3 on 2022-06-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20220507_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('AP', 'Access Point'), ('BX', 'Box'), ('CA', 'Card Printer'), ('CH', 'Chromebook'), ('CP', 'Computer'), ('LO', 'Loaned Hardware'), ('MN', 'Monitor'), ('OT', 'Other'), ('PR', 'Traditional Printer'), ('PH', 'Phone'), ('RD', 'Radio'), ('RT', 'Router'), ('SV', 'Server'), ('SW', 'Networking Switch'), ('TB', 'Tablet')], max_length=2),
        ),
    ]
