# Generated by Django 3.2.4 on 2021-06-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConBadgeLevelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regfoxPath', models.CharField(max_length=100)),
                ('regfoxValue', models.CharField(max_length=100)),
                ('badgeLevel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('regfoxPageCode', models.CharField(max_length=100)),
                ('timeLastSync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenData', models.JSONField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('timeCompleted', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rId', models.CharField(blank=True, help_text='Regfox ID', max_length=50, null=True)),
                ('displayId', models.CharField(blank=True, max_length=100, null=True)),
                ('formId', models.CharField(blank=True, max_length=100, null=True)),
                ('formName', models.CharField(blank=True, max_length=100, null=True)),
                ('formAccRef', models.CharField(blank=True, max_length=100, null=True)),
                ('orderCustomerId', models.CharField(blank=True, max_length=100, null=True)),
                ('customerId', models.CharField(blank=True, max_length=100, null=True)),
                ('orderId', models.CharField(blank=True, max_length=100, null=True)),
                ('orderDisplayId', models.CharField(blank=True, max_length=100, null=True)),
                ('orderNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('orderEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('outstandingAmount', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('fieldData', models.JSONField(blank=True, null=True)),
                ('metadata', models.CharField(blank=True, max_length=100, null=True)),
                ('checkedIn', models.BooleanField(default=False)),
                ('dateCreated', models.CharField(blank=True, max_length=100, null=True)),
                ('dateUpdated', models.CharField(blank=True, max_length=100, null=True)),
                ('conCheckedIn', models.BooleanField(default=False)),
                ('conCheckedInDate', models.DateTimeField(blank=True, null=True)),
                ('conCreepFlag', models.BooleanField(default=False)),
                ('conRegNotes', models.TextField(blank=True, null=True)),
                ('conBadgeNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('conFirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('conLastName', models.CharField(blank=True, max_length=100, null=True)),
                ('conEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('conDOB', models.CharField(blank=True, max_length=100, null=True)),
                ('conBadgeName', models.CharField(blank=True, max_length=100, null=True)),
                ('conRegLevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.conbadgelevelmap')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.event')),
            ],
        ),
        migrations.AddField(
            model_name='conbadgelevelmap',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
        ),
    ]
