# Generated by Django 3.2.4 on 2021-07-25 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uniqueBadgeNumbers',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='NEW', max_length=5)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrantdata')),
            ],
        ),
    ]
