# Generated by Django 3.2.4 on 2021-07-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210725_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantdata',
            name='conIsDealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrantdata',
            name='conIsDealerAssistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrantdata',
            name='conIsStaff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrantdata',
            name='conStaffDepartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
