# Generated by Django 3.2.4 on 2021-08-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210725_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='conbadgelevelmap',
            name='badgeImageLocation',
            field=models.CharField(default='Hello', max_length=250),
            preserve_default=False,
        ),
    ]
