# Generated by Django 3.2.4 on 2021-08-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_printjob_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantdata',
            name='hasMealPlan',
            field=models.BooleanField(default=False),
        ),
    ]
