# Generated by Django 3.2.4 on 2022-01-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_registrantdata_hasmealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banList',
            field=models.TextField(blank=True, help_text='Enter a First/Last name, or known Con Badge Name. One entry per line. Security will be notified if this name is detected.', null=True),
        ),
        migrations.AddField(
            model_name='registrantdata',
            name='conBanFlag',
            field=models.BooleanField(default=False),
        ),
    ]
