# Generated by Django 3.2.4 on 2022-04-05 22:23

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('furry', '0010_roommonitor_roommonitorhistory'),
        ('registration', '0008_registrantdata_isforwarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantdata',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='furry.profile'),
        ),
        migrations.AddField(
            model_name='registrantdata',
            name='customUploadPicture',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.upload_path_image),
        ),
        migrations.AddField(
            model_name='registrantdata',
            name='isCustomPicture',
            field=models.BooleanField(default=False),
        ),
    ]
