# Generated by Django 3.1.3 on 2022-05-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20220405_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.event'),
        ),
    ]
