# Generated by Django 3.1.3 on 2022-06-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_badge_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='regfoxStaffPageCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
