# Generated by Django 3.1.3 on 2022-06-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_event_regfoxstaffpagecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isSecAccessEnabled',
            field=models.BooleanField(default=False, help_text='Enables the PocketSec application to be used by PSafe'),
        ),
    ]
