# Generated by Django 3.1.3 on 2022-07-02 17:28

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_event_issecaccessenabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantdata',
            name='croppedImage',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.upload_cropped_image_path),
        ),
    ]
