# Generated by Django 4.0.4 on 2022-07-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_registrantdata_croppedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrantdata',
            name='vetoBadgePic',
            field=models.BooleanField(default=False),
        ),
    ]
