# Generated by Django 4.0.4 on 2022-07-26 03:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('furry', '0011_registrantassociationkey'),
        ('registration', '0014_registrantdata_vetobadgepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(default=[])),
                ('openDate', models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 45353, tzinfo=utc))),
                ('closeDate', models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 45373, tzinfo=utc))),
                ('description', models.TextField()),
                ('showOnSidebar', models.BooleanField(default=True, help_text='Shows on Dashboard Sidebar as an Application to submit for')),
                ('showOnHomepage', models.BooleanField(default=True, help_text='Shows to Guests before login on the Homepage.')),
                ('showOnDashboard', models.BooleanField(default=True, help_text='Shows on the dashboard submission tracker on the right-hand side.')),
                ('departmentBelong', models.ForeignKey(blank=True, help_text='If not set, will only be seeable by administrators.', null=True, on_delete=django.db.models.deletion.CASCADE, to='furry.department')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='aaClose',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 44690, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='aaOpen',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 44678, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='dealersClose',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 44666, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='dealersOpen',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 44654, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='eventsClose',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 44714, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='eventsOpen',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 44702, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='regClose',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 44615, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='regEditClose',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 44642, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='regEditOpen',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 44630, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='regOpen',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 3, 21, 32, 44583, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ApplicationSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_details', models.JSONField(default=[])),
                ('dateEntered', models.DateTimeField(auto_now_add=True)),
                ('disposition', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Submitted', max_length=20)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.application')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
        ),
    ]
