# Generated by Django 4.0.4 on 2023-01-15 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_application_closedate_and_more'),
        ('registration', '0020_alter_application_closedate_and_more'),
    ]

    operations = [
    ]
