# Generated by Django 4.0.4 on 2023-01-15 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_alter_application_closedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='closeDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 210726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='application',
            name='openDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 210688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='aaClose',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 209299, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='aaOpen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 209278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealersClose',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 209240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealersOpen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 209220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventsClose',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 209350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventsOpen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 209329, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='regClose',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 209152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='regEditClose',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 209199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='regEditOpen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 209178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='regOpen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 58, 42, 209107, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='webconnexaction',
            name='id',
            field=models.CharField(default=registration.models.StringKeyGenerator.__call__, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
