# Generated by Django 4.0.4 on 2023-06-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_alter_application_closedate_and_more'),
        ('registration', '0021_alter_application_closedate_and_more'),
        ('registration', '0029_alter_application_closedate_and_more'),
        ('registration', '0033_registrantdata_ruuid_alter_application_closedate_and_more'),
        ('registration', '0039_alter_application_closedate_and_more'),
    ]

    operations = [
    ]
