# Generated by Django 4.2.4 on 2023-08-17 14:40

import datetime
from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_registrantdata_a11y_chair_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrantdata',
            old_name='a11y_chair',
            new_name='a11yChair',
        ),
        migrations.RenameField(
            model_name='registrantdata',
            old_name='a11y_elevator',
            new_name='a11yElevator',
        ),
        migrations.RenameField(
            model_name='registrantdata',
            old_name='a11y_eyesight',
            new_name='a11yEyesight',
        ),
        migrations.RenameField(
            model_name='registrantdata',
            old_name='a11y_full_assist',
            new_name='a11yFullAssist',
        ),
        migrations.RenameField(
            model_name='registrantdata',
            old_name='a11y_group',
            new_name='a11yGroup',
        ),
        migrations.RenameField(
            model_name='registrantdata',
            old_name='a11y_notes',
            new_name='a11yNotes',
        ),
        migrations.RenameField(
            model_name='registrantdata',
            old_name='a11y_partial_assist',
            new_name='a11yPartialAssist',
        ),
        migrations.AlterField(
            model_name='application',
            name='closeDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 968253, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='application',
            name='openDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 968248, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='aaClose',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 967990, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='aaOpen',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 967987, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealersClose',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 967984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealersOpen',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 967981, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventsClose',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 967996, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventsOpen',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 967993, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='regClose',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 967972, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='regEditClose',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 967978, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='regEditOpen',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 967975, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='regOpen',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 14, 39, 56, 967962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='webconnexaction',
            name='id',
            field=models.CharField(default=registration.models.StringKeyGenerator.__call__, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
