# Generated by Django 3.2.9 on 2021-11-14 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_auto_20211114_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Message Created')),
                ('recieved', models.DateTimeField(editable=False, null=True, verbose_name='Message Recieved')),
                ('opened', models.DateTimeField(editable=False, null=True, verbose_name='Message Opened')),
                ('read', models.DateTimeField(editable=False, null=True, verbose_name='Message Read')),
                ('type', models.TextField(max_length=200, verbose_name='Message Type')),
                ('subject', models.TextField(verbose_name='Message subject')),
                ('slug', models.TextField(verbose_name='Message Hash Slug')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Dest Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Notification Created')),
                ('recieved', models.DateTimeField(editable=False, null=True, verbose_name='Notification Recieved')),
                ('opened', models.DateTimeField(editable=False, null=True, verbose_name='Notification Opened')),
                ('read', models.DateTimeField(editable=False, null=True, verbose_name='Notification Read')),
                ('type', models.TextField(max_length=200, verbose_name='Notification Type')),
                ('label', models.TextField(verbose_name='Notification Label')),
                ('slug', models.TextField(verbose_name='Notification Hash Slug')),
                ('contents', models.TextField(verbose_name='Notification Contents')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Dest Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile')),
            ],
        ),
        migrations.CreateModel(
            name='MessageContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='Message Contents')),
                ('attach', models.TextField(verbose_name='Message Attachments')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comms.message', verbose_name='Parent Message')),
            ],
        ),
    ]
