# Generated by Django 3.2.9 on 2021-11-14 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontents',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagecontents',
            name='updated',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Recieved'),
        ),
    ]
