# Generated by Django 4.0.2 on 2022-04-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Dest Profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile'),
        ),
        migrations.AddField(
            model_name='messagecontents',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comms.message', verbose_name='Parent Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Dest Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile'),
        ),
    ]
