# Generated by Django 4.0.2 on 2022-02-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_auto_20211114_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='message',
            name='source',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='source',
        ),
    ]
