# Generated by Django 4.0.2 on 2022-02-18 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_profilepermission_profile_profilepermission_visitor'),
        ('comms', '0003_remove_message_dest_remove_message_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dest',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Dest Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='dest',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Dest Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile'),
            preserve_default=False,
        ),
    ]
