# Generated by Django 4.2.4 on 2023-10-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_galleryfavourite_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='galleryitemsbycollectionpermission',
            table='media_gallery_core_collection_permission_view',
        ),
    ]
