# Generated by Django 4.2.4 on 2024-04-14 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0024_alter_communitysidebarmenu_module_and_more"),
        ("core", "0005_alter_galleryitemsbycollectionpermission_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryCoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_gallery",
                    models.BooleanField(
                        default=False,
                        help_text="Enable/Disable the Gallery module globally for the community. (This does not delete any files that already exist if disabled.)",
                        verbose_name="Enable Gallery Module",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="community.community",
                        unique=True,
                        verbose_name="Community",
                    ),
                ),
            ],
            options={
                "db_table": "media_gallery_core_settings",
            },
        ),
    ]
