# Generated by Django 4.2.4 on 2024-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_gallerycoresettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerycoresettings",
            name="enable_stream_integration",
            field=models.BooleanField(
                default=True,
                help_text="Enabling Gallery/Stream integration will enable users to automatically publish new gallery content to streams.",
                verbose_name="Enable Gallery/Stream Integration",
            ),
        ),
    ]
