# Generated by Django 4.2.4 on 2024-04-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_gallerycoresettings_enable_stream_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerycoresettings",
            name="enable_fed_publishing",
            field=models.BooleanField(
                default=True,
                help_text="Enabling Gallery Federation will enable users to Federate their galleries.",
                verbose_name="Enable Gallery Federation Publishing",
            ),
        ),
        migrations.AddField(
            model_name="gallerycoresettings",
            name="enable_group_galleries",
            field=models.BooleanField(
                default=True,
                help_text="Allow Groups to create and own galleries?",
                verbose_name="Enable Galleries for User Groups",
            ),
        ),
        migrations.AddField(
            model_name="gallerycoresettings",
            name="enable_rss_publishing",
            field=models.BooleanField(
                default=True,
                help_text="Enabling Gallery RSS publishing allows users to create RSS stream(s) to broadcast new gallery content.",
                verbose_name="Enable Gallery RSS Publishing",
            ),
        ),
        migrations.AlterField(
            model_name="gallerycoresettings",
            name="enable_stream_integration",
            field=models.BooleanField(
                default=True,
                help_text="Enabling Gallery/Stream integration will enable users to automatically publish new gallery content to streams.",
                verbose_name="Enable Gallery<->Stream Integration",
            ),
        ),
    ]
