# Generated by Django 4.2.4 on 2024-04-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_gallerycoresettings_enable_fed_publishing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerycoresettings",
            name="enable_metrics",
            field=models.BooleanField(
                default=True,
                help_text="Enable the Gallery Metrics module to collect insight on traffic and usage patterns (and share it with the authors.)",
                verbose_name="Enable Gallery Metrics",
            ),
        ),
        migrations.AddField(
            model_name="gallerycoresettings",
            name="gallery_max_filesize",
            field=models.IntegerField(
                default=25,
                help_text="The absolute maximum file size allowed in the Gallery in megabytes. All modules are limited by this parameter.",
                verbose_name="Maximum File Size in MB",
            ),
        ),
    ]
