# Generated by Django 4.2.4 on 2024-04-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_gallerycoresettings_enable_metrics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryPlugins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        unique=True, verbose_name="Application/plugin name"
                    ),
                ),
                ("name", models.CharField(verbose_name="Plugin's Human-readable name")),
                (
                    "descr",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Plugin's Human-friendly description",
                    ),
                ),
                ("author", models.CharField(verbose_name="Plugin's Author")),
                ("version", models.CharField(verbose_name="Plugin's Version")),
                (
                    "url",
                    models.CharField(blank=True, verbose_name="Plugin's URL: Homepage"),
                ),
                ("repo", models.CharField(verbose_name="Plugin's URL: Repository")),
                (
                    "installed",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Plugin Installed Date"
                    ),
                ),
            ],
            options={
                "db_table": "media_gallery_core_plugins",
            },
        ),
        migrations.CreateModel(
            name="GalleryPluginVersionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_version", models.CharField(verbose_name="Plugin's Old Version")),
                ("version", models.CharField(verbose_name="Plugin's Current Version")),
                (
                    "url",
                    models.CharField(blank=True, verbose_name="Plugin's URL: Homepage"),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Plugin Installed Date"
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.galleryplugins",
                    ),
                ),
            ],
            options={
                "db_table": "media_gallery_core_plugin_version_history",
            },
        ),
    ]
