# Generated by Django 4.2.4 on 2024-04-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_galleryplugins_gallerypluginversionhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerypluginversionhistory",
            name="url",
        ),
        migrations.AlterField(
            model_name="galleryplugins",
            name="author",
            field=models.CharField(null=True, verbose_name="Plugin's Author"),
        ),
        migrations.AlterField(
            model_name="galleryplugins",
            name="name",
            field=models.CharField(
                null=True, verbose_name="Plugin's Human-readable name"
            ),
        ),
        migrations.AlterField(
            model_name="galleryplugins",
            name="repo",
            field=models.CharField(null=True, verbose_name="Plugin's URL: Repository"),
        ),
        migrations.AlterField(
            model_name="galleryplugins",
            name="version",
            field=models.CharField(null=True, verbose_name="Plugin's Version"),
        ),
    ]
