# Generated by Django 4.2.4 on 2024-04-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_gallerypluginversionhistory_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryplugins",
            name="version",
            field=models.CharField(default="0.0.0", verbose_name="Plugin's Version"),
        ),
    ]
