# Generated by Django 4.2.4 on 2024-04-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0024_alter_communitysidebarmenu_module_and_more"),
        ("core", "0012_alter_galleryplugins_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryEnabledPlugins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="Plugin Enabled"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="community.community",
                        verbose_name="Community",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.galleryplugins",
                        verbose_name="Gallery Plugin",
                    ),
                ),
            ],
            options={
                "db_table": "media_gallery_core_enabled_plugins",
                "unique_together": {("community", "plugin")},
            },
        ),
    ]
