# Generated by Django 4.2.4 on 2024-04-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_gallerycoresettings_enabled_plugins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryplugins",
            name="icon",
            field=models.CharField(
                null=True, verbose_name="Plugin's Icon for Sidebars"
            ),
        ),
    ]
