# Generated by Django 5.0.1 on 2024-04-29 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_galleryplugins_settings_model"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerycollection",
            name="owner",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                to="profiles.profile",
                verbose_name="Collection Owner",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="gallerycollection",
            unique_together={("collection_id", "owner")},
        ),
    ]
