# Generated by Django 5.0.1 on 2024-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_gallerycollection_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerytempfile",
            name="userdata",
            field=models.JSONField(
                blank=True, null=True, verbose_name="File User Review JSONData"
            ),
        ),
    ]
