# Generated by Django 5.0.1 on 2024-07-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_table"),
        ("core", "0020_alter_gallerytempfile_userdata"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
                verbose_name="Item Category",
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                verbose_name="Item Owner",
            ),
        ),
        migrations.AlterField(
            model_name="galleryitemcomments",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.galleryitem",
                verbose_name="Item",
            ),
        ),
        migrations.AlterField(
            model_name="galleryitemkeyword",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.galleryitem",
                verbose_name="Item",
            ),
        ),
    ]
