# Generated by Django 5.0.1 on 2024-08-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_galleryitem_category_alter_galleryitem_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerytempfile",
            name="meta",
            field=models.JSONField(blank=True, null=True, verbose_name="File Metadata"),
        ),
    ]
