# Generated by Django 5.0.1 on 2024-08-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_gallerytempfile_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerytempfile",
            name="file_size",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="File Size"
            ),
        ),
        migrations.AlterField(
            model_name="gallerytempfile",
            name="meta",
            field=models.JSONField(
                blank=True, default={}, null=True, verbose_name="File Metadata"
            ),
        ),
        migrations.AlterField(
            model_name="gallerytempfile",
            name="plugin",
            field=models.TextField(blank=True, null=True, verbose_name="File Plugin"),
        ),
        migrations.AlterField(
            model_name="gallerytempfile",
            name="thumbnail",
            field=models.TextField(
                blank=True, null=True, verbose_name="File Thumbnail"
            ),
        ),
        migrations.AlterField(
            model_name="gallerytempfile",
            name="type",
            field=models.TextField(blank=True, null=True, verbose_name="File Type"),
        ),
    ]
