# Generated by Django 4.0.2 on 2022-02-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageText',
            new_name='AlmanacPageText',
        ),
    ]
