# Generated by Django 4.0.2 on 2022-04-26 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('almanac', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynapages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almanacpage',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Creator Profile'),
        ),
        migrations.AddField(
            model_name='almanacpage',
            name='dynaPage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='dynapages.templates', verbose_name='DynaPage Template'),
        ),
        migrations.AddField(
            model_name='almanacpage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='almanacmenucategoryentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almanac.almanacmenucategory', verbose_name='AlmanacMenu Category'),
        ),
        migrations.AddField(
            model_name='almanacmenucategoryentry',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almanac.almanacpage', verbose_name='AlmanacPage'),
        ),
    ]
