# Generated by Django 4.0.2 on 2022-02-23 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0002_rename_pagetext_almanacpagetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmanacMenuCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.TextField(max_length=200, unique=True, verbose_name='MenuCat ID')),
                ('icon', models.TextField(max_length=200, verbose_name='MenuCat Icon')),
                ('title', models.TextField(max_length=200, verbose_name='MenuCat Title')),
                ('order', models.IntegerField(default=0, verbose_name='Order Count')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
        ),
        migrations.AddField(
            model_name='almanacpage',
            name='title',
            field=models.TextField(default='', max_length=200, verbose_name='Page Title'),
            preserve_default=False,
        ),
    ]
