# Generated by Django 4.0.2 on 2022-02-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0003_almanacmenucategory_almanacpage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmanacMenuCategoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order Count')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almanac.almanacmenucategory', verbose_name='AlmanacMenu Category')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almanac.almanacpage', verbose_name='AlmanacPage')),
            ],
        ),
    ]
