# Generated by Django 4.0.2 on 2022-02-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0004_almanacmenucategoryentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almanacpagetext',
            name='page_contents',
        ),
    ]
