# Generated by Django 4.0.2 on 2022-02-25 16:52

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0005_remove_almanacpagetext_page_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='almanacpagetext',
            name='page_contents',
            field=martor.models.MartorField(default='', verbose_name='Page Contents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='almanacpagetext',
            name='language',
            field=models.TextField(default='en-US', max_length=5, verbose_name='Page Language'),
        ),
    ]
