# Generated by Django 4.0.2 on 2022-03-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_communityadmins_active'),
        ('almanac', '0006_almanacpagetext_page_contents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almanacpage',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
            preserve_default=False,
        ),
    ]
