# Generated by Django 4.0.2 on 2022-03-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0007_almanacpage_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almanacpage',
            name='dynaPage',
        ),
    ]
