# Generated by Django 4.0.2 on 2022-03-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynapages', '0021_remove_widget_widget_id_widget_widget_name'),
        ('almanac', '0008_remove_almanacpage_dynapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='almanacpage',
            name='dynaPage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='dynapages.templates', verbose_name='DynaPage Template'),
        ),
    ]
