# Generated by Django 4.2.4 on 2023-08-15 20:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLAgent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Agent First seen')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('last_view', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last Viewed')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('online', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'roleplaying_slhud_sl_agent',
            },
        ),
        migrations.CreateModel(
            name='SLHUDSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Settings Created/updated')),
                ('hud_title', models.TextField(max_length=200, unique=True, verbose_name='HUD Title (World Name)')),
                ('hud_intro', models.TextField(max_length=200, unique=True, verbose_name='HUD Introduction (World Name)')),
                ('max_profiles', models.IntegerField(default=3, verbose_name='Max Profiles Allowed')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('online', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'roleplaying_sl_hud_settings',
            },
        ),
        migrations.CreateModel(
            name='SLParcel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Agent First seen')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('online', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'roleplaying_slhud_sl_parcel',
            },
        ),
        migrations.CreateModel(
            name='SLParcelAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='Agent Last seen')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Agent UUID')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('active', models.BooleanField(default=False, verbose_name='Active FLAG')),
                ('online', models.BooleanField(default=False, verbose_name='Online FLAG')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLHUD.slparcel', verbose_name='Parcel')),
            ],
            options={
                'db_table': 'roleplaying_sl_parcel_agent',
            },
        ),
    ]
