# Generated by Django 4.0.4 on 2022-08-22 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_profilepagenodes_profilepagenode'),
        ('community', '0006_alter_communityprofile_profile'),
        ('plyscript', '0004_script_unique_funcname_script_unique_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRegistry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=1000, verbose_name='Registry Key')),
                ('contents_text', models.TextField(verbose_name='Value (Text)')),
                ('contents_json', models.TextField(null=True, verbose_name='Value (JSON)')),
                ('contents_bin', models.BinaryField(null=True, verbose_name='Value (BIN)')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profile')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plyscript.script', verbose_name='Registry')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scriptregistry',
            constraint=models.UniqueConstraint(fields=('community', 'profile', 'script', 'key'), name='unique_keyperpr'),
        ),
    ]
