# Generated by Django 4.2.4 on 2023-08-15 20:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Group Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Profile Updated')),
                ('name', models.TextField(verbose_name='Name')),
                ('impressum', models.TextField(verbose_name='Impressum')),
                ('avatar', models.TextField(null=True, verbose_name='Avatar URL')),
                ('posts', models.IntegerField(default=0, verbose_name='Post Count')),
                ('views', models.IntegerField(default=0, verbose_name='Post Count')),
                ('members', models.IntegerField(default=0, verbose_name='Member Count')),
                ('nodes', models.IntegerField(default=0, verbose_name='Node Count')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'communities_group_group',
            },
        ),
        migrations.CreateModel(
            name='GroupKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Order Column')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
            ],
            options={
                'db_table': 'communities_group_group_keywords',
            },
        ),
        migrations.CreateModel(
            name='GroupTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Title')),
                ('order', models.IntegerField(default=0, verbose_name='Order Column')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group')),
            ],
            options={
                'db_table': 'communities_group_group_title',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='group.group', verbose_name='Group')),
            ],
            options={
                'db_table': 'communities_group_group_memeber',
            },
        ),
    ]
