# Generated by Django 4.2.4 on 2023-08-15 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=1, verbose_name='Level (Numeric Value)')),
                ('name', models.TextField(verbose_name='Name')),
                ('expr', models.IntegerField(default=0, verbose_name='Experience Required')),
                ('statpoints', models.IntegerField(default=5, verbose_name='Stat Points Awarded')),
                ('skillpoints', models.IntegerField(default=2, verbose_name='Skill Points Awarded')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked FLAG')),
                ('frozen', models.BooleanField(default=False, verbose_name='Frozen FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
            ],
            options={
                'db_table': 'roleplaying_exp_level',
            },
        ),
        migrations.CreateModel(
            name='LevelScript',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'roleplaying_exp_level_script',
            },
        ),
        migrations.CreateModel(
            name='ProfileExperience',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expr', models.IntegerField(default=0, verbose_name='Current Experience')),
                ('statpoints', models.IntegerField(default=0, verbose_name='Stat Points Available')),
                ('skillpoints', models.IntegerField(default=0, verbose_name='Skill Points Available')),
            ],
            options={
                'db_table': 'roleplaying_exp_profile_experience',
            },
        ),
        migrations.CreateModel(
            name='ProfileExperienceHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expr', models.IntegerField(default=0, verbose_name='Current Experience')),
                ('statpoints', models.IntegerField(default=0, verbose_name='Stat Points Assigned')),
                ('skillpoints', models.IntegerField(default=0, verbose_name='Skill Points Assigned')),
                ('reason', models.TextField(verbose_name='Logged Reason')),
            ],
            options={
                'db_table': 'roleplaying_exp_profile_experience_history',
            },
        ),
    ]
