# Generated by Django 4.2.4 on 2023-08-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('stats', '0001_initial'),
        ('exp', '0001_initial'),
        ('community', '0002_initial'),
        ('plyscript', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileexperiencehistory',
            name='classtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stats.classtype', verbose_name='Class Type'),
        ),
        migrations.AddField(
            model_name='profileexperiencehistory',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='profileexperiencehistory',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exp.level', verbose_name='Current Level'),
        ),
        migrations.AddField(
            model_name='profileexperiencehistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='profileexperience',
            name='classtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stats.classtype', verbose_name='Class Type'),
        ),
        migrations.AddField(
            model_name='profileexperience',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='profileexperience',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exp.level', verbose_name='Current Level'),
        ),
        migrations.AddField(
            model_name='profileexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='levelscript',
            name='classtype',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='stats.classtype', verbose_name='Class Type'),
        ),
        migrations.AddField(
            model_name='levelscript',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='levelscript',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exp.level', verbose_name='Level Reached'),
        ),
        migrations.AddField(
            model_name='levelscript',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plyscript.script', verbose_name='Script Callable'),
        ),
        migrations.AddField(
            model_name='level',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='level',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plyscript.script', verbose_name='Run Script on Awarding Level'),
        ),
        migrations.AddConstraint(
            model_name='profileexperience',
            constraint=models.UniqueConstraint(fields=('community', 'profile'), name='unique_profile_exp'),
        ),
        migrations.AddConstraint(
            model_name='levelscript',
            constraint=models.UniqueConstraint(fields=('community', 'classtype', 'script', 'level'), name='unique_class_level_script'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('community', 'level'), name='unique_level'),
        ),
    ]
