# Generated by Django 3.2.4 on 2021-12-31 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0006_staffapplication_closeapp"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffOnboardRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("fanName", models.CharField(max_length=100)),
                ("dateOfBirth", models.DateField()),
                ("email", models.EmailField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        help_text="In this format: +1 555 555 5555", max_length=100
                    ),
                ),
                ("telegramHandle", models.CharField(max_length=100)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("Staff", "Staff Member"),
                            (
                                "Department Assistant Director",
                                "Department Assistant Director",
                            ),
                            ("Department Director", "Department Director"),
                            ("Board Member", "Board Member"),
                        ],
                        default="Staff",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Custom Title",
                    ),
                ),
                (
                    "displayNameAs",
                    models.CharField(
                        choices=[
                            ("0", "<First Name> <Last Name>"),
                            ("1", "<Fan Name> <Last Name>"),
                            ("2", "<Fan Name>"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "usernameAs",
                    models.CharField(
                        choices=[
                            ("0", "<Fan Name>@staff.furrydelphia.org"),
                            ("1", "<First Initial><Last Name>@staff.furrydelphia.org"),
                            (
                                "2",
                                "<Fan Name First Initial><Last Name>@staff.furrydelphia.org",
                            ),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.department",
                    ),
                ),
                (
                    "openPosition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.openposition",
                    ),
                ),
            ],
        ),
    ]
