# Generated by Django 3.2.4 on 2021-12-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffonboardrecord",
            name="codedPassword",
            field=models.CharField(
                blank=True,
                help_text="Do not enter anything in this field. Will be overwritten by the microsoft API for security purposes.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staffonboardrecord",
            name="created",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="staffonboardrecord",
            name="email",
            field=models.EmailField(
                help_text="This will be the e-mail address used to send a welcome letter to the staff member.",
                max_length=100,
            ),
        ),
    ]
