# Generated by Django 3.2.4 on 2021-12-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_onboarding", "0003_auto_20211231_1747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffonboardrecord",
            name="rank",
            field=models.CharField(
                choices=[
                    ("Staff", "Staff Member"),
                    ("Department Assistant Director", "Department Assistant Director"),
                    ("Department Director", "Department Director"),
                ],
                default="Staff",
                max_length=100,
            ),
        ),
    ]
