# Generated by Django 3.2.4 on 2022-06-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_onboarding', '0005_alter_staffonboardrecord_telegramhandle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffonboardrecord',
            options={'permissions': [('can_see_hr', 'Can see the HR Portal')]},
        ),
    ]
