# Generated by Django 3.2.9 on 2021-11-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(max_length=200, verbose_name='Keyword')),
                ('hash', models.TextField(max_length=200, verbose_name='Hash')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Item Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='tem Updated')),
                ('items', models.IntegerField(default=0, verbose_name='Item Count')),
                ('views', models.IntegerField(default=0, verbose_name='Views Count')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes Count')),
                ('shares', models.IntegerField(default=0, verbose_name='Shares Count')),
                ('comments', models.IntegerField(default=0, verbose_name='Comment Count')),
            ],
        ),
    ]
