# Generated by Django 3.2.9 on 2021-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active FLAG'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived FLAG'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden FLAG'),
        ),
    ]
