# Generated by Django 3.2.9 on 2021-11-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_auto_20211125_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='DisLikes Count'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active FLAG'),
        ),
    ]
