# Generated by Django 4.0.2 on 2022-05-10 16:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0005_friend_community'),
        ('profiles', '0002_remove_friend_friend1_remove_friend_friend2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Relationship Created')),
                ('type', models.TextField(verbose_name='Notification Type')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Notification Icon')),
                ('contents_text', models.TextField(blank=True, null=True, verbose_name='Notification Content: Text Type')),
                ('contents_json', models.JSONField(blank=True, null=True, verbose_name='Notification Content: JSON Type')),
                ('contents_bin', models.BinaryField(blank=True, null=True, verbose_name='Notification Content: Binary Type')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived FLAG')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden FLAG')),
                ('system', models.BooleanField(default=False, verbose_name='System FLAG')),
                ('delivered', models.BooleanField(default=False, verbose_name='DELIVERED FLAG')),
                ('processed', models.BooleanField(default=False, verbose_name='PROCESSED FLAG')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='profiles.profile', verbose_name='Source Profile')),
            ],
        ),
    ]
