# Generated by Django 4.0.2 on 2022-05-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_notifications'),
        ('community', '0005_friend_community'),
        ('notifications', '0002_notificationinbox'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationinbox',
            unique_together={('notification', 'community', 'recipient')},
        ),
    ]
