# Generated by Django 4.0.4 on 2022-06-06 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_notifications'),
        ('community', '0005_friend_community'),
        ('notifications', '0007_alter_mentions_deleted_alter_mentions_deleted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTotalNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Index Updated')),
                ('notifications', models.IntegerField(default=0, verbose_name='Notification Count')),
                ('messages', models.IntegerField(default=0, verbose_name='Messages Count')),
                ('mentions', models.IntegerField(default=0, verbose_name='Mentions Count')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='Community')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.profile', verbose_name='Source Profile')),
            ],
            options={
                'unique_together': {('profile', 'community')},
            },
        ),
    ]
