# Generated by Django 4.0.4 on 2022-06-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_profiletotalnotifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileTotalNotifications',
        ),
    ]
