# Generated by Django 4.0.4 on 2023-01-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='conDescription',
            new_name='atcon_description',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='atconFacebook',
            new_name='atcon_facebook',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='atconFurAffinity',
            new_name='atcon_furAffinity',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='atconInstagram',
            new_name='atcon_instagram',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='open',
            new_name='atcon_open',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='showContact',
            new_name='atcon_showContact',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='showSocialMedia',
            new_name='atcon_showSocialMedia',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='showWebsite',
            new_name='atcon_showWebsite',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='atconTwitter',
            new_name='atcon_twitter',
        ),
        migrations.AddField(
            model_name='dealer',
            name='dba_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='dba_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealer',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='qs_business_registration_location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='qs_license_already_obtained',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
