# Generated by Django 4.0.4 on 2023-01-15 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_condescription_dealer_atcon_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='backup_table_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_table_size', to='marketplace.tablesize'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='table_size',
            field=models.ForeignKey(help_text='Select the size of table you would like to have.', on_delete=django.db.models.deletion.CASCADE, related_name='table_size', to='marketplace.tablesize'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='type_of_wares',
            field=models.CharField(choices=[('dig', 'Digital Art (prints, comics, badges, etc)'), ('tra', 'Traditional Art (pencils and markets, paintings, etc)'), ('fur', 'Fursuit Maker, Accessories, and Prefabs'), ('fug', 'Fursuit Suiting Supplies & Accessories'), ('mus', 'Music or Audio'), ('bok', 'Books / Literature / Published Comics'), ('app', 'Apparel (shirts, hoodies, bandanas, etc.)'), ('acc', 'Accessories (harnesses, collars, jewelry, etc)'), ('trg', 'Traditional Games (board games, card games, etc)'), ('vid', 'Video Games (games, consoles, accessories, etc.)'), ('scu', 'Sculptures (figurines, 3D Printed models, etc.)'), ('oth', 'Other (Unique Items or Services)')], help_text='What will you primarially be selling?', max_length=5),
        ),
    ]
