# Generated by Django 4.0.4 on 2023-03-03 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0003_dealer_backup_table_size_alter_dealer_table_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistalley',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='artistalley',
            name='selling',
        ),
        migrations.AddField(
            model_name='artistalley',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artistalley',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Legal Last Name'),
        ),
        migrations.AddField(
            model_name='artistalley',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Legal Last Name'),
        ),
        migrations.AddField(
            model_name='artistalley',
            name='types_of_wares',
            field=models.CharField(blank=True, choices=[('dig', 'Digital Art (prints, comics, badges, etc)'), ('tra', 'Traditional Art (pencils and markets, paintings, etc)'), ('fur', 'Fursuit Maker, Accessories, and Prefabs'), ('fug', 'Fursuit Suiting Supplies & Accessories'), ('mus', 'Music or Audio'), ('bok', 'Books / Literature / Published Comics'), ('app', 'Apparel (shirts, hoodies, bandanas, etc.)'), ('acc', 'Accessories (harnesses, collars, jewelry, etc)'), ('trg', 'Traditional Games (board games, card games, etc)'), ('vid', 'Video Games (games, consoles, accessories, etc.)'), ('scu', 'Sculptures (figurines, 3D Printed models, etc.)'), ('oth', 'Other (Unique Items or Services)')], help_text='Must Select At Least One', max_length=200, null=True, verbose_name='What Will You Be Selling?'),
        ),
        migrations.AlterField(
            model_name='artistalley',
            name='assigned_day',
            field=models.CharField(blank=True, choices=[('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artistalley',
            name='availability',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], help_text='Must Select At Least One. You will only receive one day unless we are underbooked.', max_length=200, verbose_name='What Days Will you Be Available?'),
        ),
        migrations.AlterField(
            model_name='artistalley',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Legal First Name'),
        ),
        migrations.AlterField(
            model_name='artistalley',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Legal Last Name'),
        ),
    ]
