# Generated by Django 4.0.4 on 2023-03-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_phone_number_artistalley_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistalley',
            name='types_of_wares',
            field=models.CharField(choices=[('dig', 'Digital Art (prints, comics, badges, etc)'), ('tra', 'Traditional Art (pencils and markets, paintings, etc)'), ('fur', 'Fursuit Maker, Accessories, and Prefabs'), ('fug', 'Fursuit Suiting Supplies & Accessories'), ('mus', 'Music or Audio'), ('bok', 'Books / Literature / Published Comics'), ('app', 'Apparel (shirts, hoodies, bandanas, etc.)'), ('acc', 'Accessories (harnesses, collars, jewelry, etc)'), ('trg', 'Traditional Games (board games, card games, etc)'), ('vid', 'Video Games (games, consoles, accessories, etc.)'), ('scu', 'Sculptures (figurines, 3D Printed models, etc.)'), ('oth', 'Other (Unique Items or Services)')], default='tra', help_text='Must Select At Least One', max_length=200),
            preserve_default=False,
        ),
    ]
