# Generated by Django 4.0.4 on 2023-03-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_artistalley_types_of_wares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistalley',
            name='phone',
            field=models.CharField(help_text='Furrydelphia will only contact you via phone in the event of an emergency.', max_length=25),
        ),
    ]
