# Generated by Django 4.0.4 on 2023-03-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_artistalley_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='number',
            field=models.CharField(blank=True, default='0', max_length=2, null=True),
        ),
    ]
