# Generated by Django 4.2.4 on 2024-04-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("community", "0024_alter_communitysidebarmenu_module_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryPhotoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gallery_max_filesize",
                    models.IntegerField(
                        default=25,
                        help_text="The absolute maximum file size allowed in the Gallery in megabytes. All modules are limited by this parameter.",
                        verbose_name="Maximum File Size in MB",
                    ),
                ),
                (
                    "enable_exif",
                    models.BooleanField(
                        default=True,
                        help_text="Enable EXIF Parsing Features",
                        verbose_name="Enable EXIF Parsing",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="community.community",
                        unique=True,
                        verbose_name="Community",
                    ),
                ),
            ],
            options={
                "db_table": "media_gallery_photo_settings",
            },
        ),
    ]
